// СЛОВАРЬ панели «Map settings» — десять языков (правило 4г), англ. фолбэк. Region Quiz: беседа с
// уточнениями → сверка с каталогом Geofabrik → чекбоксы доступных регионов (размер·время) → загрузить.
export type MapPanelStrings = {
  title: string
  intro: string
  osrm: string; geocoder: string; currentRegion: string; reload: string; downloading: string
  quizGreeting: string; askPh: string; thinking: string
  checkLabel: string; noneFound: string; download: string; provisioningNote: string
  loadError: string; noKey: string
}

const D: Record<string, MapPanelStrings> = {
  en: { title: "Map settings", intro: "Maps, routing and address search for your automations — self-hosted on free OpenStreetMap data, any region on Earth, no third-party keys.", osrm: "Routing", geocoder: "Address search", currentRegion: "Active region", reload: "Refresh", downloading: "Loading", quizGreeting: "Which places do you need maps for? Name the cities or areas — I'll ask if anything's unclear and pick the available regions.", askPh: "Your answer…", thinking: "Thinking…", checkLabel: "Check the regions to download — size and time are shown honestly", noneFound: "Nothing available was found. Try naming the country or a larger area.", download: "Download & apply", provisioningNote: "Loading runs in the background; bigger regions take longer. Several checked regions are merged into one. Address search comes online when it finishes.", loadError: "Could not reach the geo service.", noKey: "Set an OpenAI key in Brain or Memory settings to use the region assistant." },
  ru: { title: "Настройка карт", intro: "Карты, маршруты и поиск по адресу для ваших автоматизаций — свои, на бесплатных данных OpenStreetMap, любой регион мира, без чужих ключей.", osrm: "Маршруты", geocoder: "Поиск по адресу", currentRegion: "Активный регион", reload: "Обновить", downloading: "Загрузка", quizGreeting: "Карты каких мест вам нужны? Назовите города или районы — я уточню, если что-то неоднозначно, и подберу доступные регионы.", askPh: "Ваш ответ…", thinking: "Думаю…", checkLabel: "Отметьте регионы для загрузки — размер и время показаны честно", noneFound: "Доступного не нашлось. Попробуйте назвать страну или более крупную область.", download: "Загрузить и применить", provisioningNote: "Загрузка идёт в фоне; крупные регионы дольше. Несколько отмеченных регионов склеиваются в один. Поиск по адресу заработает по завершении.", loadError: "Гео-сервис недоступен.", noKey: "Задайте ключ OpenAI в настройках Brain/Memory, чтобы работал помощник по регионам." },
  es: { title: "Ajustes de mapas", intro: "Mapas, rutas y búsqueda de direcciones — propios, con datos gratuitos de OpenStreetMap, cualquier región del mundo, sin claves de terceros.", osrm: "Rutas", geocoder: "Búsqueda de direcciones", currentRegion: "Región activa", reload: "Actualizar", downloading: "Cargando", quizGreeting: "¿Para qué lugares necesitas mapas? Nombra las ciudades o zonas — preguntaré si algo no está claro y elegiré las regiones disponibles.", askPh: "Tu respuesta…", thinking: "Pensando…", checkLabel: "Marca las regiones a descargar — se muestran tamaño y tiempo", noneFound: "No se encontró nada. Prueba a nombrar el país o una zona más grande.", download: "Descargar y aplicar", provisioningNote: "La carga ocurre en segundo plano; las regiones grandes tardan más. Varias regiones marcadas se fusionan en una. La búsqueda de direcciones se activa al terminar.", loadError: "Servicio geo no disponible.", noKey: "Configura una clave OpenAI en Brain/Memory para usar el asistente de regiones." },
  fr: { title: "Paramètres des cartes", intro: "Cartes, itinéraires et recherche d'adresse — auto-hébergés sur données OpenStreetMap gratuites, n'importe quelle région du monde, sans clés tierces.", osrm: "Itinéraires", geocoder: "Recherche d'adresse", currentRegion: "Région active", reload: "Actualiser", downloading: "Chargement", quizGreeting: "De quels lieux avez-vous besoin des cartes ? Nommez les villes ou zones — je préciserai si besoin et choisirai les régions disponibles.", askPh: "Votre réponse…", thinking: "Réflexion…", checkLabel: "Cochez les régions à télécharger — taille et durée affichées", noneFound: "Rien trouvé. Essayez de nommer le pays ou une zone plus large.", download: "Télécharger et appliquer", provisioningNote: "Le chargement se fait en arrière-plan ; les grandes régions prennent plus de temps. Plusieurs régions cochées sont fusionnées en une. La recherche d'adresse s'active à la fin.", loadError: "Service géo injoignable.", noKey: "Configurez une clé OpenAI dans Brain/Memory pour l'assistant de régions." },
  it: { title: "Impostazioni mappe", intro: "Mappe, percorsi e ricerca indirizzi — self-hosted su dati OpenStreetMap gratuiti, qualsiasi regione del mondo, senza chiavi di terzi.", osrm: "Percorsi", geocoder: "Ricerca indirizzi", currentRegion: "Regione attiva", reload: "Aggiorna", downloading: "Caricamento", quizGreeting: "Di quali luoghi ti servono le mappe? Indica città o zone — chiederò se qualcosa non è chiaro e sceglierò le regioni disponibili.", askPh: "La tua risposta…", thinking: "Sto pensando…", checkLabel: "Spunta le regioni da scaricare — dimensione e tempo mostrati", noneFound: "Nulla trovato. Prova a indicare il paese o un'area più ampia.", download: "Scarica e applica", provisioningNote: "Il caricamento gira in background; le regioni grandi richiedono più tempo. Più regioni spuntate vengono unite in una. La ricerca indirizzi si attiva al termine.", loadError: "Servizio geo non raggiungibile.", noKey: "Imposta una chiave OpenAI in Brain/Memory per l'assistente delle regioni." },
  de: { title: "Karten-Einstellungen", intro: "Karten, Routing und Adresssuche — selbst gehostet auf freien OpenStreetMap-Daten, jede Region der Welt, ohne Fremdschlüssel.", osrm: "Routing", geocoder: "Adresssuche", currentRegion: "Aktive Region", reload: "Aktualisieren", downloading: "Wird geladen", quizGreeting: "Für welche Orte brauchen Sie Karten? Nennen Sie Städte oder Gebiete — ich frage bei Unklarheiten nach und wähle die verfügbaren Regionen.", askPh: "Ihre Antwort…", thinking: "Denke nach…", checkLabel: "Regionen zum Herunterladen ankreuzen — Größe und Zeit werden gezeigt", noneFound: "Nichts gefunden. Nennen Sie das Land oder ein größeres Gebiet.", download: "Herunterladen & anwenden", provisioningNote: "Das Laden läuft im Hintergrund; große Regionen dauern länger. Mehrere angekreuzte Regionen werden zu einer zusammengeführt. Die Adresssuche wird am Ende aktiv.", loadError: "Geo-Dienst nicht erreichbar.", noKey: "Legen Sie in Brain/Memory einen OpenAI-Schlüssel für den Regionen-Assistenten fest." },
  pt: { title: "Definições de mapas", intro: "Mapas, rotas e pesquisa de moradas — próprios, com dados gratuitos OpenStreetMap, qualquer região do mundo, sem chaves de terceiros.", osrm: "Rotas", geocoder: "Pesquisa de moradas", currentRegion: "Região ativa", reload: "Atualizar", downloading: "A carregar", quizGreeting: "De que lugares precisa de mapas? Indique cidades ou zonas — pergunto se algo não estiver claro e escolho as regiões disponíveis.", askPh: "A sua resposta…", thinking: "A pensar…", checkLabel: "Marque as regiões a descarregar — tamanho e tempo mostrados", noneFound: "Nada encontrado. Tente indicar o país ou uma área maior.", download: "Descarregar e aplicar", provisioningNote: "O carregamento corre em segundo plano; regiões grandes demoram mais. Várias regiões marcadas são fundidas numa. A pesquisa de moradas fica ativa no fim.", loadError: "Serviço geo indisponível.", noKey: "Defina uma chave OpenAI em Brain/Memory para o assistente de regiões." },
  pl: { title: "Ustawienia map", intro: "Mapy, trasy i wyszukiwanie adresów — własne, na darmowych danych OpenStreetMap, dowolny region świata, bez obcych kluczy.", osrm: "Trasy", geocoder: "Wyszukiwanie adresów", currentRegion: "Aktywny region", reload: "Odśwież", downloading: "Ładowanie", quizGreeting: "Map jakich miejsc potrzebujesz? Podaj miasta lub obszary — dopytam, jeśli coś jest niejasne, i wybiorę dostępne regiony.", askPh: "Twoja odpowiedź…", thinking: "Myślę…", checkLabel: "Zaznacz regiony do pobrania — rozmiar i czas pokazane", noneFound: "Nic nie znaleziono. Spróbuj podać kraj lub większy obszar.", download: "Pobierz i zastosuj", provisioningNote: "Ładowanie działa w tle; duże regiony trwają dłużej. Kilka zaznaczonych regionów łączy się w jeden. Wyszukiwanie adresów włączy się po zakończeniu.", loadError: "Usługa geo niedostępna.", noKey: "Ustaw klucz OpenAI w Brain/Memory, aby użyć asystenta regionów." },
  tr: { title: "Harita ayarları", intro: "Harita, rota ve adres arama — kendi sunucunuzda, ücretsiz OpenStreetMap verisiyle, dünyanın herhangi bir bölgesi, üçüncü taraf anahtarı olmadan.", osrm: "Rota", geocoder: "Adres arama", currentRegion: "Etkin bölge", reload: "Yenile", downloading: "Yükleniyor", quizGreeting: "Hangi yerlerin haritası lazım? Şehirleri veya bölgeleri yazın — belirsizse sorarım ve mevcut bölgeleri seçerim.", askPh: "Yanıtınız…", thinking: "Düşünüyorum…", checkLabel: "İndirilecek bölgeleri işaretleyin — boyut ve süre gösterilir", noneFound: "Bir şey bulunamadı. Ülkeyi veya daha büyük bir alanı belirtin.", download: "İndir ve uygula", provisioningNote: "Yükleme arka planda çalışır; büyük bölgeler daha uzun sürer. İşaretli birden çok bölge tek bir veri kümesinde birleştirilir. Adres arama bitince devreye girer.", loadError: "Geo servisine ulaşılamadı.", noKey: "Bölge asistanı için Brain/Memory'de bir OpenAI anahtarı ayarlayın." },
  nl: { title: "Kaartinstellingen", intro: "Kaarten, routes en adres zoeken — zelf gehost op gratis OpenStreetMap-data, elke regio ter wereld, zonder sleutels van derden.", osrm: "Routes", geocoder: "Adres zoeken", currentRegion: "Actieve regio", reload: "Vernieuwen", downloading: "Laden", quizGreeting: "Van welke plaatsen heb je kaarten nodig? Noem steden of gebieden — ik vraag door als iets onduidelijk is en kies de beschikbare regio's.", askPh: "Je antwoord…", thinking: "Aan het denken…", checkLabel: "Vink de regio's aan om te downloaden — grootte en tijd worden getoond", noneFound: "Niets gevonden. Probeer het land of een groter gebied te noemen.", download: "Downloaden & toepassen", provisioningNote: "Laden draait op de achtergrond; grote regio's duren langer. Meerdere aangevinkte regio's worden samengevoegd tot één. Adres zoeken komt online als het klaar is.", loadError: "Geo-service onbereikbaar.", noKey: "Stel een OpenAI-sleutel in bij Brain/Memory om de regio-assistent te gebruiken." },
}

export function mapPanelStrings(lang: string): MapPanelStrings {
  return D[lang] ?? D.en
}
