import { NextRequest } from "next/server"
import { shouldBypassAuth } from "@/lib/auth-bypass"

// API-route gate for the migrated service endpoints (/api/glossary,
// /api/project/default/architecture/*, …). Mirrors the slot's apiAuthGate: the
// admin proxy.ts EXCLUDES /api/* from its matcher, so these handlers must guard
// themselves. Three ways in (step 135 mutation gate — tightened in Secure mode):
//   1. IP/onboarding mode (shouldBypassAuth) — fully open (onboarding surface).
//   2. An agent/MCP call carrying x-agent-identity. In IP mode the bare header is
//      accepted (surface is open anyway). In SECURE mode the header MUST be
//      accompanied by the internal secret x-agent-secret == HERMES_MCP_SECRET (the
//      same secret the MCP bridges guard with); a bare header is NO LONGER trusted.
//      This closes the pre-135 hole where anyone reaching :3002 could set the header
//      and mutate. If the secret is not configured, agent calls fail closed.
//   3. A human with the architect role — verified against the auth service by cookie.
// The service PAGES themselves are gated by the admin proxy.ts (architect-only in
// Secure mode, open in IP mode) — no per-page guard needed.

const AUTH_SERVICE = process.env.AUTH_SERVICE_URL ?? "http://localhost:3001"
// Shared internal secret — generated by bootstrap.sh (HERMES_MCP_SECRET), present in
// the fractera-admin process env and identical to the value the MCP bridges require.
const AGENT_SECRET = process.env.HERMES_MCP_SECRET ?? null

export type ServiceIdentity = {
  userId: string
  email: string
  roles: string[]
}

export async function serviceApiIdentity(req: NextRequest): Promise<ServiceIdentity | null> {
  const agentId = req.headers.get("x-agent-identity")
  if (agentId) {
    // IP/onboarding mode: the whole surface is open → bare header accepted (parity).
    if (shouldBypassAuth()) {
      return { userId: `${agentId}@agent`, email: `${agentId}@agent`, roles: ["agent"] }
    }
    // Secure mode (step 135): the agent header is trusted ONLY with the internal secret.
    const agentSecret = req.headers.get("x-agent-secret") ?? ""
    if (AGENT_SECRET && agentSecret === AGENT_SECRET) {
      return { userId: `${agentId}@agent`, email: `${agentId}@agent`, roles: ["agent"] }
    }
    return null
  }

  if (shouldBypassAuth()) {
    return { userId: "demo@local", email: "demo@local", roles: ["architect"] }
  }

  const cookie = req.headers.get("cookie") ?? ""
  if (!cookie) return null
  try {
    const res = await fetch(`${AUTH_SERVICE}/api/session`, {
      headers: { cookie },
      signal: AbortSignal.timeout(3000),
    })
    if (!res.ok) return null
    const data = (await res.json()) as ServiceIdentity | null
    if (data && Array.isArray(data.roles) && data.roles.includes("architect")) return data
    return null
  } catch {
    return null
  }
}

// Boolean helper for handlers that only need pass/deny.
export async function serviceApiGate(req: NextRequest): Promise<boolean> {
  return (await serviceApiIdentity(req)) !== null
}
