// СЛОВАРЬ ФОРМЫ КЛЮЧЕЙ — десять языков (закон 4г), англ. фолбэк. Общий примитив, поэтому и словарь
// общий: форму ключей открывают и главное меню, и календарь, и всё, что появится дальше.
export type KeysStrings = {
  connect: string; // "{k}" — имя канала
  intro: string;
  save: string;
  cancel: string;
  saving: string;
  failed: string;
  optional: string;
  alreadySet: string;
  keepValue: string;
  missing: string; // "{k}" — сколько ключей не хватает
  noKeys: string;
  change: string;
  // Нативное связывание Telegram (шаг 296)
  linkBtn: string; // кнопка «Связать мой Telegram»
  linkOpening: string; // «Открываю Telegram…»
  linkWaiting: string; // «Нажмите Start у бота — жду…»
  linkDone: string; // "{k}" — кто связан
  linkFailed: string; // не удалось / истёк код
};

export const KEYS_I18N: Record<string, KeysStrings> = {
  en: { change: "Change", connect: "Connect {k}", intro: "The channel works only once these are filled in. They are stored as project settings and are never shown again.", save: "Save and turn on", cancel: "Cancel", saving: "Saving…", failed: "The keys could not be saved.", optional: "optional", alreadySet: "already set", keepValue: "Leave empty to keep the current value.", missing: "{k} key(s) missing", noKeys: "This channel needs no keys.", linkBtn: "Link my Telegram", linkOpening: "Opening Telegram…", linkWaiting: "Tap Start in the bot — waiting…", linkDone: "Linked: {k}", linkFailed: "Could not link — try again." },
  es: { change: "Cambiar", connect: "Conectar {k}", intro: "El canal funciona solo cuando estén rellenados. Se guardan como ajustes del proyecto y no se vuelven a mostrar.", save: "Guardar y activar", cancel: "Cancelar", saving: "Guardando…", failed: "No se han podido guardar las claves.", optional: "opcional", alreadySet: "ya configurada", keepValue: "Déjalo vacío para conservar el valor actual.", missing: "faltan {k} clave(s)", noKeys: "Este canal no necesita claves.", linkBtn: "Vincular mi Telegram", linkOpening: "Abriendo Telegram…", linkWaiting: "Pulsa Iniciar en el bot — esperando…", linkDone: "Vinculado: {k}", linkFailed: "No se pudo vincular — inténtalo de nuevo." },
  fr: { change: "Modifier", connect: "Connecter {k}", intro: "Le canal ne fonctionne qu'une fois ceci renseigné. Ces valeurs sont enregistrées comme réglages du projet et ne sont plus jamais affichées.", save: "Enregistrer et activer", cancel: "Annuler", saving: "Enregistrement…", failed: "Les clés n'ont pas pu être enregistrées.", optional: "facultatif", alreadySet: "déjà renseignée", keepValue: "Laissez vide pour conserver la valeur actuelle.", missing: "{k} clé(s) manquante(s)", noKeys: "Ce canal n'a besoin d'aucune clé.", linkBtn: "Lier mon Telegram", linkOpening: "Ouverture de Telegram…", linkWaiting: "Appuyez sur Démarrer dans le bot — en attente…", linkDone: "Lié : {k}", linkFailed: "Impossible de lier — réessayez." },
  it: { change: "Modifica", connect: "Collega {k}", intro: "Il canale funziona solo quando questi sono compilati. Vengono salvati come impostazioni del progetto e non vengono più mostrati.", save: "Salva e attiva", cancel: "Annulla", saving: "Salvataggio…", failed: "Non è stato possibile salvare le chiavi.", optional: "facoltativo", alreadySet: "già impostata", keepValue: "Lascia vuoto per mantenere il valore attuale.", missing: "mancano {k} chiave/i", noKeys: "Questo canale non richiede chiavi.", linkBtn: "Collega il mio Telegram", linkOpening: "Apro Telegram…", linkWaiting: "Tocca Avvia nel bot — in attesa…", linkDone: "Collegato: {k}", linkFailed: "Collegamento non riuscito — riprova." },
  ru: { change: "Изменить", connect: "Подключить {k}", intro: "Канал заработает, только когда это заполнено. Значения хранятся как настройки проекта и больше никогда не показываются.", save: "Сохранить и включить", cancel: "Отмена", saving: "Сохраняю…", failed: "Сохранить ключи не удалось.", optional: "необязательно", alreadySet: "уже задан", keepValue: "Оставьте пустым, чтобы сохранить текущее значение.", missing: "не хватает ключей: {k}", noKeys: "Этому каналу ключи не нужны.", linkBtn: "Связать мой Telegram", linkOpening: "Открываю Telegram…", linkWaiting: "Нажмите Start у бота — жду…", linkDone: "Связано: {k}", linkFailed: "Связать не удалось — попробуйте ещё раз." },
  de: { change: "Ändern", connect: "{k} verbinden", intro: "Der Kanal arbeitet erst, wenn dies ausgefüllt ist. Die Werte werden als Projekteinstellungen gespeichert und nie wieder angezeigt.", save: "Speichern und einschalten", cancel: "Abbrechen", saving: "Speichern…", failed: "Die Schlüssel konnten nicht gespeichert werden.", optional: "optional", alreadySet: "bereits gesetzt", keepValue: "Leer lassen, um den aktuellen Wert zu behalten.", missing: "{k} Schlüssel fehlen", noKeys: "Dieser Kanal braucht keine Schlüssel.", linkBtn: "Mein Telegram verknüpfen", linkOpening: "Telegram wird geöffnet…", linkWaiting: "Tippen Sie im Bot auf Start — warte…", linkDone: "Verknüpft: {k}", linkFailed: "Verknüpfen fehlgeschlagen — erneut versuchen." },
  pt: { change: "Alterar", connect: "Ligar {k}", intro: "O canal só funciona depois de isto preenchido. Os valores ficam como definições do projeto e nunca mais são mostrados.", save: "Guardar e ligar", cancel: "Cancelar", saving: "A guardar…", failed: "Não foi possível guardar as chaves.", optional: "opcional", alreadySet: "já definida", keepValue: "Deixe vazio para manter o valor atual.", missing: "faltam {k} chave(s)", noKeys: "Este canal não precisa de chaves.", linkBtn: "Ligar o meu Telegram", linkOpening: "A abrir o Telegram…", linkWaiting: "Toque em Iniciar no bot — a aguardar…", linkDone: "Ligado: {k}", linkFailed: "Não foi possível ligar — tente novamente." },
  pl: { change: "Zmień", connect: "Podłącz {k}", intro: "Kanał zadziała dopiero po wypełnieniu. Wartości są zapisywane jako ustawienia projektu i nigdy więcej nie są pokazywane.", save: "Zapisz i włącz", cancel: "Anuluj", saving: "Zapisywanie…", failed: "Nie udało się zapisać kluczy.", optional: "opcjonalne", alreadySet: "już ustawiony", keepValue: "Zostaw puste, aby zachować bieżącą wartość.", missing: "brakuje kluczy: {k}", noKeys: "Ten kanał nie potrzebuje kluczy.", linkBtn: "Połącz mój Telegram", linkOpening: "Otwieram Telegram…", linkWaiting: "Naciśnij Start w bocie — czekam…", linkDone: "Połączono: {k}", linkFailed: "Nie udało się połączyć — spróbuj ponownie." },
  tr: { change: "Değiştir", connect: "{k} bağla", intro: "Kanal ancak bunlar doldurulunca çalışır. Değerler proje ayarı olarak saklanır ve bir daha gösterilmez.", save: "Kaydet ve aç", cancel: "İptal", saving: "Kaydediliyor…", failed: "Anahtarlar kaydedilemedi.", optional: "isteğe bağlı", alreadySet: "zaten ayarlı", keepValue: "Mevcut değeri korumak için boş bırakın.", missing: "{k} anahtar eksik", noKeys: "Bu kanal anahtar gerektirmiyor.", linkBtn: "Telegram'ımı bağla", linkOpening: "Telegram açılıyor…", linkWaiting: "Botta Başlat'a dokunun — bekleniyor…", linkDone: "Bağlandı: {k}", linkFailed: "Bağlanamadı — tekrar deneyin." },
  nl: { change: "Wijzigen", connect: "{k} verbinden", intro: "Het kanaal werkt pas als dit is ingevuld. De waarden worden als projectinstelling bewaard en nooit meer getoond.", save: "Opslaan en aanzetten", cancel: "Annuleren", saving: "Opslaan…", failed: "De sleutels konden niet worden opgeslagen.", optional: "optioneel", alreadySet: "al ingesteld", keepValue: "Laat leeg om de huidige waarde te behouden.", missing: "{k} sleutel(s) ontbreken", noKeys: "Dit kanaal heeft geen sleutels nodig.", linkBtn: "Mijn Telegram koppelen", linkOpening: "Telegram openen…", linkWaiting: "Tik op Start in de bot — wachten…", linkDone: "Gekoppeld: {k}", linkFailed: "Koppelen mislukt — probeer opnieuw." },
};

export const keysStrings = (lang: string): KeysStrings => KEYS_I18N[lang.slice(0, 2)] ?? KEYS_I18N.en;
