// СЛОВАРЬ ШАПКИ — десять языков (en, es, fr, it, ru, de, pt, pl, tr, nl), англ. фолбэк (закон 4г).
// Живёт в папке автоматизации: наружу не ходим (закон 0). Метки меню перенесены ДОСЛОВНО из v1
// (automation-menu-i18n.ts) — фидбэк владельца «переноси один-в-один». Переводим только прозу
// интерфейса; значения enum (тип/жизненный цикл/шаринг) остаются машинными токенами (закон 4г).
export type ChromeStrings = {
  // menu chrome (faithful to v1)
  menuAria: string;
  howItWorks: string;
  automationLabel: string;
  aiProvider: string;
  aiModel: string;
  entitiesHeading: string;
  reorderAria: string; // "{name}"
  settingsItem: string;
  testsItem: string;
  dangerZone: string;
  renameAutomation: string;
  cloneAutomation: string;
  deleteAutomation: string;
  // channels section of the menu (step 293)
  aiSaveFailed: string;
  aiKeyHint: string;
  aiModelsUnavailable: string;
  channelsHeading: string;
  channelsIn: string;
  channelsOut: string;
  channelNeedsKeys: string;
  channelNoFunction: string;
  // added in v2 (the ONE new entry the owner asked for) + the no-backend placeholder
  placeholderNote: string;
  // how-it-works modal body (public Sparkle + menu item)
  howItWorksEmpty: string;
  // how-it-works SERVICE (step 302): frozen gate toast + the generate/refine flow
  howItWorksFrozen: string; // toast: build the automation first
  howItWorksIntro: string; // no-answer intro
  howItWorksGet: string; // "Get answer" button
  howItWorksAskHint: string; // no-answer form hint (optional question)
  howItWorksRefineHint: string; // answer form hint (clarifying question overwrites)
  howItWorksAskPlaceholder: string; // question textarea placeholder
  howItWorksAskSend: string; // "Send question" button
  howItWorksLoading: string; // reading the stored answer
  howItWorksFail: string; // generation failed
  // send-task
  sendOpen: string;
  sendTitle: string;
  sendPlaceholder: string;
  sendSubmit: string;
  sendSending: string;
  sendSaved: string;
  sendFailed: string;
  cancel: string;
};

const I18N: Record<string, ChromeStrings> = {
  en: { aiSaveFailed: "The choice could not be saved.", aiKeyHint: "The provider key is entered below, in its own card — one key serves every automation in the project.", channelsHeading: "Channels this automation uses", channelsIn: "Listens on", channelsOut: "Answers through", channelNeedsKeys: "keys are not set yet", channelNoFunction: "its code is not written yet", menuAria: "Automation menu", howItWorks: "How it works", automationLabel: "Automation", aiProvider: "AI provider", aiModel: "AI model", aiModelsUnavailable: "The live model list is unavailable right now.", entitiesHeading: "Sections shown on this page", reorderAria: "Reorder {name}", settingsItem: "Settings", testsItem: "Tests", dangerZone: "Danger zone", renameAutomation: "Rename this automation", cloneAutomation: "Clone this automation", deleteAutomation: "Delete this automation", placeholderNote: "This will be available in this template soon.", howItWorksEmpty: "The answer will appear here once the automation is built.", howItWorksFrozen: "First build the automation — then use this button to get information about it.", howItWorksIntro: "This explains what your automation does and how it works, generated from its current setup. Click ‘Get answer’, or ask about a specific aspect first.", howItWorksGet: "Get answer", howItWorksAskHint: "Want to focus on a specific aspect? Ask a question (optional).", howItWorksRefineHint: "Want more detail on a specific aspect? Ask a clarifying question — the new answer replaces this one.", howItWorksAskPlaceholder: "e.g. Explain the Telegram part in more detail", howItWorksAskSend: "Send question", howItWorksLoading: "Loading…", howItWorksFail: "Could not generate the answer.", sendOpen: "Send task", sendTitle: "Task for the automation", sendPlaceholder: "Describe what the automation should do…", sendSubmit: "Send", sendSending: "Sending…", sendSaved: "Task saved to the automation.", sendFailed: "Could not save the task.", cancel: "Cancel" },
  es: { aiSaveFailed: "No se ha podido guardar la elección.", aiKeyHint: "La clave del proveedor se introduce abajo, en su propia tarjeta: una clave sirve a todas las automatizaciones del proyecto.", channelsHeading: "Canales que usa esta automatización", channelsIn: "Escucha en", channelsOut: "Responde por", channelNeedsKeys: "las claves aún no están puestas", channelNoFunction: "su código aún no está escrito", menuAria: "Menú de automatización", howItWorks: "Cómo funciona", automationLabel: "Automatización", aiProvider: "Proveedor de IA", aiModel: "Modelo de IA", aiModelsUnavailable: "La lista de modelos no está disponible ahora.", entitiesHeading: "Secciones mostradas en esta página", reorderAria: "Reordenar {name}", settingsItem: "Configuración", testsItem: "Pruebas", dangerZone: "Zona de peligro", renameAutomation: "Renombrar esta automatización", cloneAutomation: "Clonar esta automatización", deleteAutomation: "Eliminar esta automatización", placeholderNote: "Esto estará disponible pronto en esta plantilla.", howItWorksEmpty: "La respuesta aparecerá aquí cuando se construya la automatización.", howItWorksFrozen: "Primero construye la automatización, luego usa este botón para obtener información sobre ella.", howItWorksIntro: "Aquí se explica qué hace tu automatización y cómo funciona, a partir de su configuración actual. Pulsa ‘Obtener respuesta’ o pregunta primero por un aspecto concreto.", howItWorksGet: "Obtener respuesta", howItWorksAskHint: "¿Quieres centrarte en un aspecto concreto? Haz una pregunta (opcional).", howItWorksRefineHint: "¿Quieres más detalle sobre un aspecto? Haz una pregunta aclaratoria: la nueva respuesta reemplaza esta.", howItWorksAskPlaceholder: "p. ej. Explica con más detalle la parte de Telegram", howItWorksAskSend: "Enviar pregunta", howItWorksLoading: "Cargando…", howItWorksFail: "No se pudo generar la respuesta.", sendOpen: "Enviar tarea", sendTitle: "Tarea para la automatización", sendPlaceholder: "Describe qué debe hacer la automatización…", sendSubmit: "Enviar", sendSending: "Enviando…", sendSaved: "Tarea guardada en la automatización.", sendFailed: "No se pudo guardar la tarea.", cancel: "Cancelar" },
  fr: { aiSaveFailed: "Le choix n'a pas pu être enregistré.", aiKeyHint: "La clé du fournisseur se saisit plus bas, dans sa propre carte — une seule clé sert toutes les automatisations du projet.", channelsHeading: "Canaux utilisés par cette automatisation", channelsIn: "Écoute sur", channelsOut: "Répond par", channelNeedsKeys: "les clés ne sont pas encore renseignées", channelNoFunction: "son code n'est pas encore écrit", menuAria: "Menu d'automatisation", howItWorks: "Comment ça marche", automationLabel: "Automatisation", aiProvider: "Fournisseur d'IA", aiModel: "Modèle d'IA", aiModelsUnavailable: "La liste des modèles est indisponible pour l'instant.", entitiesHeading: "Sections affichées sur cette page", reorderAria: "Réorganiser {name}", settingsItem: "Paramètres", testsItem: "Tests", dangerZone: "Zone de danger", renameAutomation: "Renommer cette automatisation", cloneAutomation: "Cloner cette automatisation", deleteAutomation: "Supprimer cette automatisation", placeholderNote: "Ceci sera bientôt disponible dans ce modèle.", howItWorksEmpty: "La réponse apparaîtra ici une fois l'automatisation construite.", howItWorksFrozen: "Construisez d'abord l'automatisation, puis utilisez ce bouton pour obtenir des informations.", howItWorksIntro: "Ceci explique ce que fait votre automatisation et comment elle fonctionne, d'après sa configuration actuelle. Cliquez sur ‘Obtenir la réponse’ ou posez d'abord une question sur un aspect précis.", howItWorksGet: "Obtenir la réponse", howItWorksAskHint: "Vous voulez cibler un aspect précis ? Posez une question (facultatif).", howItWorksRefineHint: "Vous voulez plus de détails sur un aspect ? Posez une question de précision — la nouvelle réponse remplace celle-ci.", howItWorksAskPlaceholder: "p. ex. Expliquez plus en détail la partie Telegram", howItWorksAskSend: "Envoyer la question", howItWorksLoading: "Chargement…", howItWorksFail: "Impossible de générer la réponse.", sendOpen: "Envoyer une tâche", sendTitle: "Tâche pour l'automatisation", sendPlaceholder: "Décrivez ce que l'automatisation doit faire…", sendSubmit: "Envoyer", sendSending: "Envoi…", sendSaved: "Tâche enregistrée dans l'automatisation.", sendFailed: "Impossible d'enregistrer la tâche.", cancel: "Annuler" },
  it: { aiSaveFailed: "Non è stato possibile salvare la scelta.", aiKeyHint: "La chiave del provider si inserisce sotto, nella sua scheda: una chiave serve tutte le automazioni del progetto.", channelsHeading: "Canali usati da questa automazione", channelsIn: "Ascolta su", channelsOut: "Risponde tramite", channelNeedsKeys: "le chiavi non sono ancora impostate", channelNoFunction: "il suo codice non è ancora scritto", menuAria: "Menu di automazione", howItWorks: "Come funziona", automationLabel: "Automazione", aiProvider: "Provider IA", aiModel: "Modello IA", aiModelsUnavailable: "L'elenco dei modelli non è disponibile ora.", entitiesHeading: "Sezioni mostrate in questa pagina", reorderAria: "Riordina {name}", settingsItem: "Impostazioni", testsItem: "Test", dangerZone: "Zona di pericolo", renameAutomation: "Rinomina questa automazione", cloneAutomation: "Clona questa automazione", deleteAutomation: "Elimina questa automazione", placeholderNote: "Sarà presto disponibile in questo modello.", howItWorksEmpty: "La risposta apparirà qui una volta costruita l'automazione.", howItWorksFrozen: "Prima costruisci l'automazione, poi usa questo pulsante per avere informazioni.", howItWorksIntro: "Qui si spiega cosa fa la tua automazione e come funziona, in base alla sua configurazione attuale. Premi ‘Ottieni risposta’ o chiedi prima di un aspetto specifico.", howItWorksGet: "Ottieni risposta", howItWorksAskHint: "Vuoi concentrarti su un aspetto specifico? Fai una domanda (facoltativo).", howItWorksRefineHint: "Vuoi più dettagli su un aspetto? Fai una domanda di chiarimento: la nuova risposta sostituisce questa.", howItWorksAskPlaceholder: "es. Spiega più in dettaglio la parte Telegram", howItWorksAskSend: "Invia domanda", howItWorksLoading: "Caricamento…", howItWorksFail: "Impossibile generare la risposta.", sendOpen: "Invia attività", sendTitle: "Attività per l'automazione", sendPlaceholder: "Descrivi cosa deve fare l'automazione…", sendSubmit: "Invia", sendSending: "Invio…", sendSaved: "Attività salvata nell'automazione.", sendFailed: "Impossibile salvare l'attività.", cancel: "Annulla" },
  ru: { aiSaveFailed: "Сохранить выбор не удалось.", aiKeyHint: "Ключ провайдера вводится ниже, в своей карточке — один ключ обслуживает все автоматизации проекта.", channelsHeading: "Каналы этой автоматизации", channelsIn: "Слушает", channelsOut: "Отвечает через", channelNeedsKeys: "ключи ещё не введены", channelNoFunction: "его код ещё не написан", menuAria: "Меню автоматизации", howItWorks: "Как это работает", automationLabel: "Автоматизация", aiProvider: "Провайдер ИИ", aiModel: "Модель ИИ", aiModelsUnavailable: "Живой список моделей сейчас недоступен.", entitiesHeading: "Разделы на этой странице", reorderAria: "Переместить {name}", settingsItem: "Настройки", testsItem: "Тесты", dangerZone: "Опасная зона", renameAutomation: "Переименовать эту автоматизацию", cloneAutomation: "Клонировать эту автоматизацию", deleteAutomation: "Удалить эту автоматизацию", placeholderNote: "Это скоро появится в этом шаблоне.", howItWorksEmpty: "Ответ появится здесь, когда автоматизация будет построена.", howItWorksFrozen: "Сначала постройте автоматизацию — затем нажмите эту кнопку, чтобы получить информацию о ней.", howItWorksIntro: "Здесь объясняется, что делает ваша автоматизация и как она работает — на основе её текущего устройства. Нажмите «Получить ответ» или сначала спросите про конкретный аспект.", howItWorksGet: "Получить ответ", howItWorksAskHint: "Нужен фокус на конкретном аспекте? Задайте вопрос (необязательно).", howItWorksRefineHint: "Нужно подробнее по конкретному аспекту? Задайте уточняющий вопрос — новый ответ заменит этот.", howItWorksAskPlaceholder: "напр. Подробнее про часть с Telegram", howItWorksAskSend: "Отправить вопрос", howItWorksLoading: "Загрузка…", howItWorksFail: "Не удалось сформировать ответ.", sendOpen: "Отправить задание", sendTitle: "Задание для автоматизации", sendPlaceholder: "Опишите, что должна делать автоматизация…", sendSubmit: "Отправить", sendSending: "Отправляю…", sendSaved: "Задание сохранено в автоматизации.", sendFailed: "Не удалось сохранить задание.", cancel: "Отмена" },
  de: { aiSaveFailed: "Die Auswahl konnte nicht gespeichert werden.", aiKeyHint: "Der Anbieter-Schlüssel wird unten in seiner eigenen Karte eingegeben — ein Schlüssel bedient alle Automatisierungen des Projekts.", channelsHeading: "Kanäle dieser Automatisierung", channelsIn: "Hört auf", channelsOut: "Antwortet über", channelNeedsKeys: "Schlüssel sind noch nicht gesetzt", channelNoFunction: "sein Code ist noch nicht geschrieben", menuAria: "Automatisierungsmenü", howItWorks: "So funktioniert es", automationLabel: "Automatisierung", aiProvider: "KI-Anbieter", aiModel: "KI-Modell", aiModelsUnavailable: "Die Modellliste ist gerade nicht verfügbar.", entitiesHeading: "Auf dieser Seite angezeigte Bereiche", reorderAria: "{name} neu anordnen", settingsItem: "Einstellungen", testsItem: "Tests", dangerZone: "Gefahrenzone", renameAutomation: "Diese Automatisierung umbenennen", cloneAutomation: "Diese Automatisierung klonen", deleteAutomation: "Diese Automatisierung löschen", placeholderNote: "Dies wird bald in dieser Vorlage verfügbar sein.", howItWorksEmpty: "Die Antwort erscheint hier, sobald die Automatisierung gebaut ist.", howItWorksFrozen: "Bauen Sie zuerst die Automatisierung — dann erhalten Sie mit dieser Schaltfläche Informationen dazu.", howItWorksIntro: "Hier wird erklärt, was Ihre Automatisierung tut und wie sie funktioniert — aus ihrem aktuellen Aufbau. Klicken Sie auf ‚Antwort erhalten‘ oder fragen Sie zuerst nach einem bestimmten Aspekt.", howItWorksGet: "Antwort erhalten", howItWorksAskHint: "Möchten Sie einen bestimmten Aspekt betonen? Stellen Sie eine Frage (optional).", howItWorksRefineHint: "Mehr Details zu einem Aspekt? Stellen Sie eine klärende Frage — die neue Antwort ersetzt diese.", howItWorksAskPlaceholder: "z. B. Erkläre den Telegram-Teil genauer", howItWorksAskSend: "Frage senden", howItWorksLoading: "Laden…", howItWorksFail: "Antwort konnte nicht erstellt werden.", sendOpen: "Aufgabe senden", sendTitle: "Aufgabe für die Automatisierung", sendPlaceholder: "Beschreiben Sie, was die Automatisierung tun soll…", sendSubmit: "Senden", sendSending: "Senden…", sendSaved: "Aufgabe in der Automatisierung gespeichert.", sendFailed: "Aufgabe konnte nicht gespeichert werden.", cancel: "Abbrechen" },
  pt: { aiSaveFailed: "Não foi possível guardar a escolha.", aiKeyHint: "A chave do fornecedor introduz-se abaixo, no seu próprio cartão — uma chave serve todas as automações do projeto.", channelsHeading: "Canais que esta automação usa", channelsIn: "Escuta em", channelsOut: "Responde por", channelNeedsKeys: "as chaves ainda não estão definidas", channelNoFunction: "o seu código ainda não está escrito", menuAria: "Menu de automação", howItWorks: "Como funciona", automationLabel: "Automação", aiProvider: "Provedor de IA", aiModel: "Modelo de IA", aiModelsUnavailable: "A lista de modelos está indisponível agora.", entitiesHeading: "Seções mostradas nesta página", reorderAria: "Reordenar {name}", settingsItem: "Configurações", testsItem: "Testes", dangerZone: "Zona de perigo", renameAutomation: "Renomear esta automação", cloneAutomation: "Clonar esta automação", deleteAutomation: "Eliminar esta automação", placeholderNote: "Isto estará disponível em breve neste modelo.", howItWorksEmpty: "A resposta aparecerá aqui quando a automação for construída.", howItWorksFrozen: "Primeiro construa a automação — depois use este botão para obter informações sobre ela.", howItWorksIntro: "Aqui explica-se o que a sua automação faz e como funciona, a partir da configuração atual. Clique em ‘Obter resposta’ ou pergunte primeiro sobre um aspeto específico.", howItWorksGet: "Obter resposta", howItWorksAskHint: "Quer focar num aspeto específico? Faça uma pergunta (opcional).", howItWorksRefineHint: "Quer mais detalhe sobre um aspeto? Faça uma pergunta de esclarecimento — a nova resposta substitui esta.", howItWorksAskPlaceholder: "ex.: Explique melhor a parte do Telegram", howItWorksAskSend: "Enviar pergunta", howItWorksLoading: "A carregar…", howItWorksFail: "Não foi possível gerar a resposta.", sendOpen: "Enviar tarefa", sendTitle: "Tarefa para a automação", sendPlaceholder: "Descreva o que a automação deve fazer…", sendSubmit: "Enviar", sendSending: "A enviar…", sendSaved: "Tarefa guardada na automação.", sendFailed: "Não foi possível guardar a tarefa.", cancel: "Cancelar" },
  pl: { aiSaveFailed: "Nie udało się zapisać wyboru.", aiKeyHint: "Klucz dostawcy wpisuje się niżej, we własnej karcie — jeden klucz obsługuje wszystkie automatyzacje projektu.", channelsHeading: "Kanały tej automatyzacji", channelsIn: "Nasłuchuje na", channelsOut: "Odpowiada przez", channelNeedsKeys: "klucze nie są jeszcze wpisane", channelNoFunction: "jego kod nie jest jeszcze napisany", menuAria: "Menu automatyzacji", howItWorks: "Jak to działa", automationLabel: "Automatyzacja", aiProvider: "Dostawca AI", aiModel: "Model AI", aiModelsUnavailable: "Lista modeli jest teraz niedostępna.", entitiesHeading: "Sekcje pokazywane na tej stronie", reorderAria: "Zmień kolejność: {name}", settingsItem: "Ustawienia", testsItem: "Testy", dangerZone: "Strefa zagrożenia", renameAutomation: "Zmień nazwę tej automatyzacji", cloneAutomation: "Sklonuj tę automatyzację", deleteAutomation: "Usuń tę automatyzację", placeholderNote: "To będzie wkrótce dostępne w tym szablonie.", howItWorksEmpty: "Odpowiedź pojawi się tutaj, gdy automatyzacja zostanie zbudowana.", howItWorksFrozen: "Najpierw zbuduj automatyzację — potem użyj tego przycisku, aby uzyskać o niej informacje.", howItWorksIntro: "Tutaj wyjaśniamy, co robi Twoja automatyzacja i jak działa, na podstawie jej obecnej konfiguracji. Kliknij ‘Uzyskaj odpowiedź’ lub najpierw zapytaj o konkretny aspekt.", howItWorksGet: "Uzyskaj odpowiedź", howItWorksAskHint: "Chcesz skupić się na konkretnym aspekcie? Zadaj pytanie (opcjonalnie).", howItWorksRefineHint: "Chcesz więcej szczegółów o jakimś aspekcie? Zadaj pytanie doprecyzowujące — nowa odpowiedź zastąpi tę.", howItWorksAskPlaceholder: "np. Wyjaśnij dokładniej część z Telegramem", howItWorksAskSend: "Wyślij pytanie", howItWorksLoading: "Ładowanie…", howItWorksFail: "Nie udało się wygenerować odpowiedzi.", sendOpen: "Wyślij zadanie", sendTitle: "Zadanie dla automatyzacji", sendPlaceholder: "Opisz, co ma robić automatyzacja…", sendSubmit: "Wyślij", sendSending: "Wysyłanie…", sendSaved: "Zadanie zapisane w automatyzacji.", sendFailed: "Nie udało się zapisać zadania.", cancel: "Anuluj" },
  tr: { aiSaveFailed: "Seçim kaydedilemedi.", aiKeyHint: "Sağlayıcı anahtarı aşağıda kendi kartında girilir — tek anahtar projedeki tüm otomasyonlara hizmet eder.", channelsHeading: "Bu otomasyonun kanalları", channelsIn: "Dinlediği", channelsOut: "Yanıtladığı", channelNeedsKeys: "anahtarlar henüz girilmedi", channelNoFunction: "kodu henüz yazılmadı", menuAria: "Otomasyon menüsü", howItWorks: "Nasıl çalışır", automationLabel: "Otomasyon", aiProvider: "AI sağlayıcı", aiModel: "AI modeli", aiModelsUnavailable: "Model listesi şu anda kullanılamıyor.", entitiesHeading: "Bu sayfada gösterilen bölümler", reorderAria: "{name} sırasını değiştir", settingsItem: "Ayarlar", testsItem: "Testler", dangerZone: "Tehlike bölgesi", renameAutomation: "Bu otomasyonu yeniden adlandır", cloneAutomation: "Bu otomasyonu klonla", deleteAutomation: "Bu otomasyonu sil", placeholderNote: "Bu, bu şablonda yakında kullanılabilir olacak.", howItWorksEmpty: "Otomasyon oluşturulduğunda yanıt burada görünecek.", howItWorksFrozen: "Önce otomasyonu oluşturun — sonra hakkında bilgi almak için bu düğmeyi kullanın.", howItWorksIntro: "Burada otomasyonunuzun ne yaptığı ve nasıl çalıştığı, mevcut yapısına göre açıklanır. ‘Yanıt al’a tıklayın ya da önce belirli bir yönü sorun.", howItWorksGet: "Yanıt al", howItWorksAskHint: "Belirli bir yöne odaklanmak ister misiniz? Bir soru sorun (isteğe bağlı).", howItWorksRefineHint: "Belirli bir yön hakkında daha fazla ayrıntı mı? Açıklayıcı bir soru sorun — yeni yanıt bunun yerine geçer.", howItWorksAskPlaceholder: "örn. Telegram kısmını daha ayrıntılı açıkla", howItWorksAskSend: "Soruyu gönder", howItWorksLoading: "Yükleniyor…", howItWorksFail: "Yanıt oluşturulamadı.", sendOpen: "Görev gönder", sendTitle: "Otomasyon için görev", sendPlaceholder: "Otomasyonun ne yapması gerektiğini açıklayın…", sendSubmit: "Gönder", sendSending: "Gönderiliyor…", sendSaved: "Görev otomasyona kaydedildi.", sendFailed: "Görev kaydedilemedi.", cancel: "İptal" },
  nl: { aiSaveFailed: "De keuze kon niet worden opgeslagen.", aiKeyHint: "De providersleutel wordt hieronder in zijn eigen kaart ingevoerd — één sleutel bedient alle automatiseringen van het project.", channelsHeading: "Kanalen van deze automatisering", channelsIn: "Luistert op", channelsOut: "Antwoordt via", channelNeedsKeys: "sleutels zijn nog niet ingevuld", channelNoFunction: "de code is nog niet geschreven", menuAria: "Automatiseringsmenu", howItWorks: "Hoe het werkt", automationLabel: "Automatisering", aiProvider: "AI-provider", aiModel: "AI-model", aiModelsUnavailable: "De modellijst is nu niet beschikbaar.", entitiesHeading: "Secties op deze pagina", reorderAria: "{name} herordenen", settingsItem: "Instellingen", testsItem: "Tests", dangerZone: "Gevarenzone", renameAutomation: "Deze automatisering hernoemen", cloneAutomation: "Deze automatisering klonen", deleteAutomation: "Deze automatisering verwijderen", placeholderNote: "Dit komt binnenkort beschikbaar in deze sjabloon.", howItWorksEmpty: "Het antwoord verschijnt hier zodra de automatisering is gebouwd.", howItWorksFrozen: "Bouw eerst de automatisering — gebruik daarna deze knop voor informatie erover.", howItWorksIntro: "Hier wordt uitgelegd wat je automatisering doet en hoe ze werkt, op basis van haar huidige opzet. Klik op ‘Antwoord ophalen’, of vraag eerst naar een specifiek aspect.", howItWorksGet: "Antwoord ophalen", howItWorksAskHint: "Wil je je op een specifiek aspect richten? Stel een vraag (optioneel).", howItWorksRefineHint: "Meer detail over een aspect? Stel een verduidelijkende vraag — het nieuwe antwoord vervangt dit.", howItWorksAskPlaceholder: "bijv. Leg het Telegram-deel uitgebreider uit", howItWorksAskSend: "Vraag versturen", howItWorksLoading: "Laden…", howItWorksFail: "Kon het antwoord niet genereren.", sendOpen: "Taak versturen", sendTitle: "Taak voor de automatisering", sendPlaceholder: "Beschrijf wat de automatisering moet doen…", sendSubmit: "Versturen", sendSending: "Versturen…", sendSaved: "Taak opgeslagen in de automatisering.", sendFailed: "Kon de taak niet opslaan.", cancel: "Annuleren" },
};

/** The chrome strings for a two-letter code, English until/unless a match is found. */
export function chromeStrings(lang: string): ChromeStrings {
  return I18N[lang.toLowerCase().slice(0, 2)] ?? I18N.en;
}

/** A machine enum token shown as a badge: never translated (rule 4г), only the hyphen turned to a space. */
export function badgeLabel(token: string): string {
  return token.replace(/-/g, " ");
}
