import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { resolveProject, listNodes, listDiagramEdges, readNodeFiles } from "@/lib/nodes";
import { listEdges, readEdgeFiles, readChainSpec, groupMembers } from "@/lib/edges";
import { listCases, reviewState } from "@/lib/use-cases";
import { getLiveEntities } from "@/lib/entities-live";
import { readHowItWorks } from "@/lib/how-it-works";
import {
  NODE_ROLE_DESCRIPTIONS, INPUT_TYPE_DESCRIPTIONS, OUTPUT_TYPE_DESCRIPTIONS, INTERMEDIATE_TYPE_DESCRIPTIONS,
} from "@/app/(projects)/projects/_shared/node-contract";
import {
  type EntityType, ENTITY_TYPES, type EntitySlice, type EntityTaskRecord, type EntityInstance,
  getTransport, getHistory, getSummary, getWarning, listVersionsByRef, makeInstance, getLifecycleState,
} from "@/lib/entity-store";
import { readEnvPresence } from "@/lib/env-presence";

export type { EntityType, EntitySlice };
export { ENTITY_TYPES };

// UNIVERSAL ENTITY ARCHITECTURE BUNDLER (step 238) — the shared library behind:
//   - the 27 per-entity sub-APIs (add-new-transport-task-entry / extract-current-state-for-architecture /
//     extract-full-history-for-architecture, one triad per entity)
//   - the two master orchestrators (fetch-complete-automation-architecture-with-history,
//     fetch-current-automation-architecture-snapshot)
//
// ⚑ WHAT THIS OBJECT IS (owner-confirmed, 2026-07-15 — recorded so it is never re-investigated): the
// ArchitectureBundle is a PURELY INFORMATIONAL representation handed to a CODING AGENT — terminal read-only
// output. `buildArchitecture` is called ONLY by the two master route handlers, and `extractEntitySlice` ONLY
// by those handlers + the per-entity route factory (entity-architecture-routes.ts); every one of them just
// serializes the result to JSON and returns it. NOTHING in the codebase consumes this object for control
// flow, state, or any programmatic logic — it exists solely so an agent reading it understands the
// automation and what is `pending`. So do NOT trace "who applies/uses this object": there are no such
// consumers by design; edits here change only what an agent READS, never runtime behaviour.
//
// This is the TOP of the entity-architecture dependency graph: it imports the domain modules (nodes/edges/
// use-cases) AND the generic storage layer (lib/entity-store.ts) to do the per-entity EXTRACTION. Nothing
// should import FROM this file except the two master routes and the 27 per-entity sub-API routes — the
// domain modules themselves (use-cases.ts, edges.ts) import storage primitives directly from
// lib/entity-store.ts, never from here, to avoid a circular module dependency.
//
// Every extractor below returns a fully-formed EntitySlice<TTask,TIdentity> (see lib/entity-store.ts for the
// contract): an array of `instances[]` — length 1 for automation-wide entities (chain/dashboard/analytics/
// calendar/map/processes, ref=''), length N for per-instance entities (node/edge/usecase, ref=cuid). Each
// instance's `pending`/`currentTask` are built via `makeInstance()` so the two can never drift apart.
//
// FOUR entities (node/edge/usecase/chain) already have real authored content today — their extractors read
// from that EXISTING storage (files + entity_history/automation_use_cases/chain-spec.md). FIVE entities
// (dashboard/analytics/calendar/map/processes) have only the free-text "Requirement" brief (step 238 P5-P9)
// as their authoring surface — their extractors report today's visibility toggle + that brief.

// ─── THE PASSPORT (the automation's own identity — the bundle's opening section) ───────────────────────
// Without it JSON1/JSON2 would carry nodes and cases of an automation whose NAME, PURPOSE and TYPE the
// reading agent never sees — the "How it works" answer would regress vs step 237 (which read README +
// description directly). The passport restores exactly that: title/description (_data/description.ts),
// the immutable type (_data/automation.ts), the owner's original instruction (_data/instruction.md),
// the README and the merged entity toggles.
//
// The passport ALSO carries `howItWorks` — the plain-language "How it works" answer the AI wrote for the
// owner (_data/how-it-works.json, generated by lib/how-it-works.ts on the modal's "Get answer from AI"
// button, step 237/238). It is EMPTY until the owner has generated it once. Surfacing it here is the whole
// point of the request: when this snapshot is handed to a coding agent, that agent reads the same human
// explanation the owner already validated, instead of re-deriving what the automation is from raw nodes.

// A fixed plain-language description of EACH automation TYPE — a deterministic dictionary in code (no model
// call). Emitted in the passport as `available_types_and_descriptions`, right next to `type`, so a reading
// coding-agent instantly grasps what KIND this automation is AND how all three kinds differ, natively in the
// object. stream/instanced stay ≤10 words; `chained` deliberately carries the full group doctrine (owner
// 2026-07-16) — how groups arise, the activation rule, and the model requirement — because the group IS the
// scale mechanism and an agent must never treat it as just "a folder of automations".
const AUTOMATION_TYPE_DESCRIPTIONS: Record<string, string> = {
  stream: "Always-on; every request handled immediately, no separate finite runs.",
  instanced: "Each request spawns an independent finite run, in parallel.",
  chained:
    "A container wiring several automations into one end-to-end flow. Group members arise two ways: " +
    "AUTOMATICALLY, when one automation outgrows the node budget (25 propose / 30 hard max) and is decomposed " +
    "for efficient development; or MANUALLY, when the owner composes several standalone automations into one " +
    "process. Production activation happens ONLY through the group; members stay individually editable and " +
    "individually test-runnable. ⚠ IMPORTANT: working on a chained group requires the MOST POWERFUL AI model " +
    "available to your coding agent — switch to it before continuing; and after development completes, the " +
    "automation must run entirely WITHOUT AI (the two-phase doctrine: design once expensively, run forever " +
    "cheaply).",
};

// ─── NODE ROLE — the bundle side (iteration 2, owner 2026-07-15) ────────────────────────────────────────
// The node entity is presented GROUPED by role (input / intermediate / output + custom), because a flat list
// hid the automation's shape from a reading agent. Each group carries a fixed, product-level SYSTEM
// INSTRUCTION — a general explanation (same for every automation) of what that role's nodes DO in the app, so
// the coding agent grasps each type's job without inferring it. The short ≤10-word dictionary
// (available_node_roles_and_descriptions) mirrors the automation-type dictionary; custom roles are allowed.
const CANONICAL_NODE_ROLES = ["input", "intermediate", "output"] as const;

// CONCEPTUAL role descriptions (owner 2026-07-15): say what the role IS and how work flows through it — NOT
// which channels exist today, and NOT how to program it. The available concrete channels/surfaces are a
// SEPARATE taxonomy carried on each group (available_types), so these stay timeless.
const NODE_ROLE_SYSTEM_INSTRUCTIONS: Record<string, string> = {
  input:
    "An INPUT node is the automation's entry point: it exists to RECEIVE incoming work and turn it into the " +
    "typed payload the rest of the flow consumes. The work arrives either from a person or from ANOTHER " +
    "automation's output node when automations are chained. An input node accepts that trigger, validates it, " +
    "and shapes it for the nodes downstream; nothing runs until it has produced a resolved input.",
  intermediate:
    "An INTERMEDIATE node is the deterministic MIDDLE of the automation: it takes what the previous node " +
    "produced and moves it toward the result — this is where the automation's real logic lives (computing, " +
    "deciding, filtering, enriching, or calling an external tool). It neither receives the original trigger " +
    "nor delivers the final result; it transforms one node's typed output into the next node's typed input. " +
    "The middle comes in TWO kinds (see available_types): a `transform` (the ordinary working node) and a " +
    "`condition` gate that branches the flow — a node's own `ioType` says which it is.",
  output:
    "An OUTPUT node is the automation's exit point: it exists to DELIVER the finished result to its " +
    "destination. That destination is a surface the user sees, an external channel, or ANOTHER automation's " +
    "input node when automations are chained. It is the last step, reached only once the work has succeeded.",
};

// ─── THE STATIC INSTRUCTION SET (owner 2026-07-16 — the rawRequest/summary refactor) ───────────────────────
// Deterministic dictionaries IN CODE, never model-generated per automation: if the AI rewrote its own
// instructions each iteration, quality would degrade like a game of broken telephone. The dynamic part of the
// object is ONLY rawRequest/summary; the law is static here. Adaptation to a concrete automation happens
// naturally: static instruction + that object's own rawRequest = an individual brief.

/** The GENERAL instruction at the top of the bundle — the reading agent's duties over the whole object. */
const AGENT_INSTRUCTION_CORE =
  "This object is the COMPLETE description of one automation. Your duties, in order: " +
  "(1) READ THIS ENTIRE OBJECT before acting. " +
  "(2) Focus on every `rawRequest` field across the object: it is the owner's wish, written in free form. An " +
  "empty string means no request for that object. Non-empty text is a requirement written by a non-programmer " +
  "in everyday language — treat it critically but constructively, and interpret it against the WHOLE " +
  "automation's structure, never in isolation. " +
  "(2a) THE LIFECYCLE FLAG — passport.lifecycleState, two verbatim states (step 247). \"starter-template\": " +
  "this automation's graph is STILL the working demo pattern shipped by the frozen template (e.g. a " +
  "stock-quote demo: parse -> external HTTP -> record). The demo exists ONLY to show you the working shape " +
  "of nodes/functions/dashboard — it carries zero weight against the owner's goal; the owner's rawRequest " +
  "and use cases ALWAYS outrank it, and reorienting, renaming or replacing demo nodes to serve the real " +
  "goal is your NORMAL first-pass work. NEVER report a demo-vs-goal mismatch as a conflict, a blocker or a " +
  "warning — it is not one. The system flips the flag itself to \"real-automation\" the first time an " +
  "object really lands (a node's materialize / an entity-summary call, step 249) — your duty is simply to " +
  "finish the objects properly. \"real-automation\": nothing is a demo anymore — every node " +
  "and entity is the owner's live behaviour; renovate it, never treat it as an example or rebuild it " +
  "silently. " +
  "(2b) SCALE ASSESSMENT IS YOUR FIRST DECISION (step 250, hard law — before ANY change): estimate the node " +
  "count the pending work implies against the node budget (AUTOMATION-PROJECTS.md §2.1: 25 nodes = " +
  "decomposition is mandatory, 30 = absolute cap). If the task would exceed the budget or inherently needs " +
  "SEVERAL automations, you make ZERO changes to this automation — no node, no edge, no file. Instead you " +
  "finish by producing a DECOMPOSITION RECOMMENDATION: the list of proposed automations, a ready-to-paste " +
  "creation instruction for each, and a grouping instruction for wiring them into a chained group — " +
  "persisted as an owner-decision warning on the `general` entity so the owner finds it later. This outcome " +
  "is a SUCCESS, not a failure or an error. " +
  "(3) Once you understand the current structure and every pending wish, develop the objects one by one — the " +
  "`diagram` FIRST (nodes and edges), then the other entities. " +
  "(4) Each object carries its own `instruction`; re-read and follow it when developing that object (an empty " +
  "instruction means no special rules for it yet). " +
  "(4a) THE SELF-SUFFICIENCY CUTOFF (step 246): before developing an object, decide honestly whether you can " +
  "finish it with the means you have. If a MISSING CAPABILITY is covered by an installable MCP tool (e.g. web " +
  "search -> exa.ai), install and wire it yourself — no warning needed. But if you are blocked on DATA or " +
  "ACCESS obtainable only by a one-off external action (credentials, captcha, login-walled scraping, fresh " +
  "data, manual registration) or on an OWNER DECISION — do NOT storm it: write a structured `warning` via " +
  "POST /api/projects/entity-warning {automation, entityType, ref, warning:{subject, blocker, kind, " +
  "hermesInstruction?, keys?, expectedAnswer?}}, set that object aside, continue the other objects, and " +
  "finish the wave with warnings in place. " +
  "(4b) PERMANENT CREDENTIALS ARE SETTINGS FIELDS, NOT A SCOUT JOB (step 248): when the blocker is keys/" +
  "tokens the automation needs PERMANENTLY to operate (a bot token, an API key pair), first read " +
  "passport.credentials — a key with present:true is already filled, never ask for it again. Missing? " +
  "(1) DECLARE the channel with its keys in _data/channels.ts (the channels standard — this is what draws " +
  "the fields in the owner's Settings modal), (2) write the warning with kind \"missing-credentials\" and " +
  "keys:[env names] — no hermesInstruction. The owner fills the keys in Settings; the system then resolves " +
  "the warning ITSELF and appends a re-test mandate to the object's rawRequest — you never got to test " +
  "without the keys, so the next iteration MUST really test before finishing. kind \"hermes-scout\" stays " +
  "for ONE-OFF data/actions (scraping, a captcha, a consent walk-through), never for permanent keys. A " +
  "secret VALUE you meet anywhere in the owner's text goes to env at once (POST /api/project-config/env) — " +
  "in specs/summaries/git only the KEY NAME, never the value. " +
  "THE WARNING IS READ BY A NON-TECHNICAL OWNER (step 247) — three layers, one " +
  "audience each: `subject` = ≤10 plain words in the owner's language naming WHAT you need (\"интеграция с " +
  "Google Calendar\"); `blocker` = 1-3 plain sentences (≤500 chars, enforced) saying what blocks you and why " +
  "— NO file paths, NO identifiers, NO quoted system stubs; `hermesInstruction` = the ONLY place for " +
  "technical detail, a first-person brief (context: what we build -> what we tried -> why it failed -> what " +
  "to do -> what to return as pasteable text). ONE warning = ONE blocker of ONE kind — never bundle two " +
  "questions; several problems = several warnings. kind \"hermes-scout\" MUST carry hermesInstruction (the " +
  "owner copies it to the Hermes agent — a one-off scout that can drive a browser and fetch such results); " +
  "write INTO it the requirement that Hermes's report begin verbatim with: \"Согласно вашему требованию я " +
  "провёл исследование и вот какие результаты я получил для вас:\". A SECOND self-attempt of the same failed " +
  "kind is FORBIDDEN, and so is faking the result with a stub. Never clear a rawRequest whose work you did " +
  "not finish — a warning and the rawRequest coexist; a warning and a summary do not. Before re-attempting an " +
  "object that carries an answered warning, read its history — the warning+answer pair is archived there and " +
  "is your context. " +
  "(5) CLOSING IS PER-OBJECT (step 249 — no global closing call): finishing a NODE = POST " +
  "/api/projects/nodes/<cuid>/materialize {summary} — it compiles the node's runtime artifact (the node is " +
  "live instantly, no rebuild; a compile error comes back in the response), records the version, archives " +
  "the node's rawRequest to history and clears it. Finishing ANY OTHER object = POST " +
  "/api/projects/entity-summary {automation, entityType, ref, summary} — it archives + clears that object's " +
  "rawRequest itself (409 while the object carries an open warning). The summary is ≤300 characters, in the " +
  "owner's own language; for a node, also keep its meta.ts `description` in sync (the summary's co-located " +
  "home). The owner reads the summary, and so will you on the next development iteration. " +
  "(6) If the passport says isChainedGroup:true, this automation is a container of other automations — its " +
  "real architecture is the `chain` slice, not its own diagram.";
// ─── THE LIFECYCLE FLAG's dictionary (step 247, owner's design) — shipped in the passport ─────────────────
const LIFECYCLE_STATE_DESCRIPTIONS: Record<string, string> = {
  "starter-template":
    "This automation's graph is still the demo pattern shipped by the frozen template. Every demo node, " +
    "table and setting is an EXAMPLE with zero weight against the owner's goal — reorient, rename or " +
    "replace them to serve the real task; never report their mismatch with the goal as a problem. The " +
    "system flips this state to real-automation at the first per-object closure that really lands " +
    "(a node materialized / an entity summarized).",
  "real-automation":
    "Development has really landed something: the graph now IS the owner's real process. Nothing here is " +
    "a demo anymore — every node/entity is live behaviour to respect, renovate and never silently rebuild.",
};

// ─── THE FIELD CONTRACTS (step 247, owner's design) — the universal trio's lifecycle, IN the JSON itself ───
// Self-describing law shipped with every bundle, so the reading agent learns the rawRequest/summary/warning
// state machine from the object it holds, without the external document. Static in code, like every other
// instruction. One correction to the owner's draft is deliberate: on BLOCKED the rawRequest is NOT cleared —
// it coexists with the warning (step 246), only SUCCESS clears it (the system archives the original).
export type FieldContract = {
  field: "rawRequest" | "summary" | "warning";
  systemRole: "trigger" | "success-state" | "blocked-state";
  instruction: string;
};

const AGENT_FIELD_CONTRACTS: FieldContract[] = [
  {
    field: "rawRequest",
    systemRole: "trigger",
    instruction:
      "The incoming development trigger. Non-empty = the owner left a wish you MUST take into development: " +
      "research the request and drive this node/edge/object to one of two terminal states — SUCCESS (you " +
      "write its summary) or BLOCKED (you write its warning). On SUCCESS the closing call clears this field " +
      "(the original is archived to history). On BLOCKED it STAYS, coexisting with the warning — the task is " +
      "not done, and the owner's answer will be appended right here to re-enter development.",
  },
  {
    field: "summary",
    systemRole: "success-state",
    instruction:
      "Written ONLY when the rawRequest's task is successfully realised. A compact text (≤300 characters, in " +
      "the owner's language) saying how this object works now: what it takes in and what it returns under " +
      "its contract. Written via POST /api/projects/entity-summary (for a node, the summary travels in its " +
      "materialize call) — that call IS the object's closure: it archives the rawRequest and clears it " +
      "(step 249). Never fill it for unfinished work.",
  },
  {
    field: "warning",
    systemRole: "blocked-state",
    instruction:
      "Written ONLY when the rawRequest's task is impossible with your means (credentials, keys, captcha, " +
      "registration, or an owner decision). Structured, three layers (agent_instruction 4a): subject = ≤10 " +
      "plain words naming the need; blocker = 1-3 plain sentences for a non-technical owner; " +
      "hermesInstruction = the technical brief for the Hermes agent. The FOUR kinds, pick exactly one: " +
      "\"hermes-scout\" = ONE-OFF data/access an external action can obtain (the Hermes agent goes and " +
      "gets it; hermesInstruction REQUIRED); \"owner-decision\" = only the owner can decide (a choice, a " +
      "payment, consent) — the blocker carries the question, no Hermes instruction; \"external-service\" = " +
      "an external service itself is down/broken/refusing and nobody can fetch around it — the owner is " +
      "informed and decides how to proceed; \"missing-credentials\" (step 248) = PERMANENT keys the " +
      "automation needs to operate — keys:[env names] REQUIRED, the same keys declared as a channel in " +
      "_data/channels.ts. Its lifecycle differs: the owner fills the keys in the Settings modal, the " +
      "system auto-resolves the warning and appends a MANDATORY re-test to the rawRequest — the next " +
      "iteration must really test with the keys before finishing. NEVER write fake stub code instead of " +
      "raising a warning. Ending your session with an object blocked-with-a-warning is a legitimate " +
      "terminal state for this iteration (the rawRequest stays for the next one).",
  },
];

const AGENT_INSTRUCTION_TAIL_FULL =
  " FORMAT NOTE: this is the FULL format — every instance also carries its complete version history[] " +
  "(oldest first). Use it at the start of a coding session or for deep debugging.";
const AGENT_INSTRUCTION_TAIL_CURRENT =
  " FORMAT NOTE: this is the CURRENT-STATE format — history[] is empty everywhere. Use it for the \"How it " +
  "works\" description, use-case debugging, or as the 2nd+ context object within an ongoing session.";

/** The DIAGRAM's own instruction — the node-building methodology (owner 2026-07-16) + the node budget. */
const DIAGRAM_INSTRUCTION =
  "The diagram (nodes + edges) is the ONLY source of truth for this automation's behaviour. Design it as an " +
  "ITERATIVE loop over nodes and edges. Recommended default order — deviate only when you can justify it: " +
  "(a) BOUNDARY FIRST — understand and fix the INPUT node and the OUTPUT node with their typed contracts, " +
  "derived from the owner's request and the use cases; " +
  "(b) add ONE main intermediate node carrying the core work; " +
  "(c) ITERATE — ask \"what else must exist for the use cases to hold?\" and add one or a few nodes per pass, " +
  "wire them with edges, fill their functions and summaries; a node exists only if a use case requires it; " +
  "(d) VERIFY — run at least TWO virtual tests: walk the diagram end-to-end on concrete example inputs, one " +
  "success path and one failure/branch path, checking every edge condition and that each edge's source output " +
  "type satisfies its target input type. " +
  "NODE BUDGET (hard law, see AUTOMATION-PROJECTS.md §2.1): at 25 nodes you MUST propose decomposition into a " +
  "chained group; 30 nodes is the absolute maximum — no new node may be added past it under ANY phrasing; " +
  "further growth happens only by decomposition. Only after the virtual tests pass move to the other entities. " +
  "RUNTIME LIMIT (until the graph executor lands — step 241): today's executor runs the nodes SEQUENTIALLY in " +
  "diagram order through one shared context bag — fan-in (several nodes feeding one) and fan-out (one node's " +
  "result read by several) WORK through the bag, but condition nodes are NOT evaluated as branch gates: every " +
  "node executes. Do not design mutually-exclusive branches — decide conditions INSIDE a node's functions " +
  "(check, then return the according result) and keep the chain a linear tree whose order respects who " +
  "produces what.";

/** The NODES group's instruction — how ANY node is built, identical for every role and type. */
const NODES_INSTRUCTION =
  "Every node is built the same way, regardless of role: take the node's `rawRequest` (the owner's free-form " +
  "wish), then (1) reformat it into a SHORT, compressed instruction written in the owner's own language; " +
  "(2) from it, design the deterministic application FUNCTIONS that fulfil the request; (3) record every " +
  "function in the node's `functions` — its name, a one-line instruction, what it takes and what it returns. " +
  "The node's `summary` (≤300 characters, owner's language) states how the node works now. The role/type only " +
  "says WHERE the node sits in the flow and WHAT KIND of work it does — never how it is built. " +
  "THE DECISION LADDER (step 246) — BEFORE building a node, answer: can I build it COMPLETELY with available " +
  "means? Strictly in order: (1) CAN DO MYSELF (deterministic code + already-wired tools) -> build. " +
  "(2) MISSING A CAPABILITY an MCP tool covers (web search -> exa.ai, etc.) -> find, install and wire it to " +
  "the node yourself, document it in functions — self-service, no warning. (3a) MISSING PERMANENT " +
  "CREDENTIALS (keys/tokens the automation needs to operate) -> check passport.credentials first " +
  "(present:true = already filled); missing -> declare the channel in _data/channels.ts AND write the " +
  "node's warning kind \"missing-credentials\" with keys:[env names] (agent_instruction 4b) — the owner " +
  "fills them in Settings, the system re-queues the node with a mandatory re-test. (3b) MISSING ONE-OFF " +
  "DATA/ACCESS (captcha, login-walled parsing, fresh data, registration) -> do NOT storm it: write the " +
  "node's `warning` kind \"hermes-scout\" (see agent_instruction 4a — subject + plain-language blocker + " +
  "technical detail ONLY in hermesInstruction), set THIS node aside, continue the others. " +
  "(4) NEEDS AN OWNER DECISION (a choice, a payment, consent) -> the same warning without a Hermes " +
  "instruction, with the question. ONE warning = ONE blocker — a node blocked by two independent problems " +
  "gets its most fundamental one first; the rest wait for the next iteration. FORBIDDEN: a second " +
  "self-attempt after a failure of the same kind; faking a result with a stub instead of a warning; calling " +
  "Hermes yourself (the system forms the call, the owner runs it); reporting the starter demo's mismatch " +
  "with the owner's goal as a warning (see agent_instruction 2a — reorienting the demo IS the job).";

/** The internal (diagram) EDGES' instruction. */
const EDGES_INSTRUCTION =
  "An edge states WHAT passes from its source node to its target node and UNDER WHAT CONDITION it is taken " +
  "(`when`; null = always taken). Diagram edges are DERIVED from each node's declared parent (meta.ts " +
  "`parentId` / the live index's parent_cuid) — to change the wiring, change the nodes' parents, never a " +
  "separate file. The source node's typed output must satisfy the target node's typed input. Several edges " +
  "leaving one parent through CONDITION nodes form a BRANCH — the DESIGN law is that exactly one is taken; " +
  "but the CURRENT executor does not evaluate edges or `when` at runtime (see the diagram instruction's " +
  "runtime limit) — until step 241 lands, decide conditions inside a node's functions instead of relying on " +
  "branch gating.";

/** Per-entity static instructions (owner 2026-07-16 — authored entity by entity). Every instruction follows
 *  one formula: what the entity IS → where its data lives → how to develop it from its rawRequest → the
 *  invariant that must never break. Empty string = not authored yet ("no special rules"). */
const ENTITY_INSTRUCTIONS: Partial<Record<EntityType, string>> = {
  node: NODES_INSTRUCTION,
  edge:
    "A LINK between two automations — one automation's output node feeding another automation's input node. " +
    "Built like every object: compress the link's rawRequest into a short statement of what crosses the " +
    "boundary and under what condition; both endpoint automations must have zero draft nodes before a link " +
    "can be created (the readiness gate).",
  usecase:
    "A USE CASE is one real scenario of this automation, in the owner's own words: who acts, what comes in, " +
    "what must come out, what happens on error. Use cases are the automation's FIRST stage and its behavioural " +
    "truth: every node must be justified by a case (no case → no node), and the diagram's virtual tests are " +
    "walked one case at a time. When a case's rawRequest changes, re-check which nodes/edges that scenario " +
    "touches and update them in the same wave. Never mark behaviour done that no case describes; never delete " +
    "a case's consequences from the diagram without the owner's confirmation (the review gate).",
  chain:
    "The CHAIN is a chained group's real architecture: its member automations and the hand-offs between them. " +
    "Develop it interface-first — design each seam as a typed contract (which member's output node feeds which " +
    "member's input node, wired as a link), before touching the members' insides. Members stay individually " +
    "comprehensible (node budget 25/30 each) and individually test-runnable; production activation is " +
    "group-only. Read memberSnapshots for each member's surface; when a member's own depth is needed, fetch " +
    "THAT member's architecture — never inline it here. Requires the most powerful model available.",
  dashboard:
    "The DASHBOARD is the automation's table surface: 0..N config-driven TABLES (this slice carries ONE " +
    "instance PER TABLE, ref = the table id, after the automation-wide instance ref='' for whole-dashboard " +
    "requirements). A table's identity is typed: its columns (closed ColumnType set — see " +
    "available_column_types) each with id/type/source, and its cell ACTIONS (available_action_types) each " +
    "with an authored plain-language actionDescription saying what the opened modal does — author it whenever " +
    "you add an action. Rows are written by output nodes (ioType \"dashboard\") through the shared row store " +
    "(lib/dashboard-rows.ts — addRow/listRows, the dashboard_rows table); the table config lives in the " +
    "automation's own _data/dashboard.ts. Develop from each table's OWN rawRequest: adjust that table's " +
    "columns to carry exactly what the owner asks to see, then make the writing node supply those values. " +
    "NEVER invent a parallel storage or a second write path — one store, written only by output nodes, read " +
    "only by the dashboard UI. A row is a RESULT: only a successful run writes one.",
  analytics:
    "ANALYTICS is the automation's chart surface: visual aggregates computed over the SAME data the automation " +
    "already records (dashboard rows, run history) — never over a copy. Develop from the rawRequest: pick the " +
    "smallest set of charts that answers the owner's question, compute aggregates server-side with " +
    "deterministic code, and state each chart's source (which table/rows, which field, which period). If the " +
    "data a chart needs is not being recorded yet, first extend the recording node — do not fabricate data.",
  calendar:
    "The CALENDAR is the automation's time surface: month and timeline views of event rows read through the " +
    "same shared row store as the dashboard (a calendar event is a row with a date). An output node with " +
    "ioType \"calendar\" writes events; the calendar only displays them. Develop from the rawRequest: define " +
    "what an event IS for this automation (title, when, what extra fields), make the writing node supply it, " +
    "and keep the display read-only — behaviour lives in the diagram, never in the calendar itself.",
  cron:
    "CRON is the automation's own timer: its settings (enabled flag + interval) live in the automation's " +
    "cron.json, edited through the Cron accordion and read by the fractera-cron runner, which fires the " +
    "automation's entry on schedule. Develop from the rawRequest: set the periodicity the owner asks for and " +
    "make sure the input node the tick fires exists and handles a scheduled (unattended) trigger — validate " +
    "inputs, fail quietly into the run log, never wait for a human. Cron STARTS work; what the work is remains " +
    "entirely the diagram's.",
  map:
    "The MAP is the automation's geo surface: markers/geo rows recorded by an output node (ioType \"map\") and " +
    "displayed read-only. Develop from the rawRequest: define what a marker means for this automation (what is " +
    "placed, from which field the coordinates come, what a click shows), make the writing node supply " +
    "coordinates + label, and keep all behaviour in the diagram — the map only shows what was recorded.",
  processes:
    "PROCESSES is the automation's Gantt/timeline surface: planned vs actual duration of runs, computed from " +
    "each node's estDurationMs (meta.ts) and the recorded runs (automation_runs / automation_schedule). " +
    "Develop from the rawRequest: keep every node's estDurationMs an honest estimate (refine it against " +
    "actual run data), and express the owner's planning wishes (ordering, expected lengths) through those " +
    "estimates and the schedule — never through hidden logic outside the diagram.",
  general:
    "GENERAL is the owner's free comment on the WHOLE automation (the Sparkles button): he does not know " +
    "which entity or node the fix belongs to — locating it is YOUR job. Read the rawRequest against the full " +
    "architecture, work out which objects it really touches, implement the change there (co-located, diagram " +
    "first), and close THIS object with a summary saying what was changed and where. If the wish is really " +
    "several independent wishes, implement them all — one general brief may fan out into several objects.",
};

/** One node role group in the bundle: the role, its (conceptual) system instruction, the finer input/output
 *  type taxonomy that applies to it (input & output only — the channels/surfaces its nodes may use, `custom`
 *  allowed), and the nodes that have this role. Each node entry ties the node to its CONCRETE `ioType` right
 *  here (e.g. this input node → "control-panel"), so the role↔type link is explicit without cross-referencing
 *  `instances[]`; `ref` is the node's cuid — look it up in `instances[]` for its full task/history/status. */
type NodeRoleGroup = {
  role: string;
  system_instruction: string;
  available_types?: Record<string, string>;
  nodes: { ref: string; name: string; ioType?: string }[];
};

/** One function INSIDE a node, as the reading agent sees it (owner 2026-07-16): its name, the one-line
 *  instruction the AI formed, and — very shortly — what it takes and what it returns. Sourced from the node's
 *  real compiled functions.ts (via the generated executables registry), never regex-guessed. */
type NodeFunctionCard = { name: string; instruction: string; takes: Record<string, string>; returns: string };

/** A node instance = the uniform EntityInstance PLUS its `functions` (the deterministic code living inside
 *  this node). A draft node has no functions yet — an empty array. */
type NodeInstance = EntityInstance<NodeTask, NodeIdentity> & { functions: NodeFunctionCard[] };

/** The node entity's slice — the uniform EntitySlice (so the one-pattern read still holds) PLUS the grouped,
 *  role-aware view an agent uses to reason about the automation's shape, and the static build law. */
type NodeArchitectureSlice = Omit<EntitySlice<NodeTask, NodeIdentity>, "instances"> & {
  instruction: string;
  available_node_roles_and_descriptions: Record<string, string>;
  custom_roles_allowed: boolean;
  role_groups: NodeRoleGroup[];
  instances: NodeInstance[];
};

/** Group the node instances by their role. Canonical roles (input → intermediate → output) always appear, in
 *  order, even when empty (so the agent sees all three slots); any custom role is appended only if used. */
function buildNodeSlice(instances: NodeInstance[]): NodeArchitectureSlice {
  const roleOf = (i: (typeof instances)[number]) => (i.identity as NodeIdentity).role;
  const customRoles = [...new Set(instances.map(roleOf))].filter((r) => !CANONICAL_NODE_ROLES.includes(r as never));
  const typesForRole = (role: string): Record<string, string> | undefined =>
    role === "input" ? INPUT_TYPE_DESCRIPTIONS
      : role === "output" ? OUTPUT_TYPE_DESCRIPTIONS
        : role === "intermediate" ? INTERMEDIATE_TYPE_DESCRIPTIONS
          : undefined;
  // Every intermediate node carries an explicit type here, so the two-kind split is always visible: a node
  // that authored no `ioType` is the DEFAULT `transform`; only a condition gate sets `ioType: "condition"`.
  const ioTypeOf = (i: (typeof instances)[number], role: string): string | undefined => {
    const t = (i.identity as NodeIdentity).ioType;
    return role === "intermediate" ? (t ?? "transform") : t;
  };
  const role_groups: NodeRoleGroup[] = [...CANONICAL_NODE_ROLES, ...customRoles].map((role) => ({
    role,
    system_instruction: NODE_ROLE_SYSTEM_INSTRUCTIONS[role] ?? "",
    available_types: typesForRole(role),
    nodes: instances
      .filter((i) => roleOf(i) === role)
      .map((i) => ({ ref: i.ref, name: (i.identity as NodeIdentity).name, ioType: ioTypeOf(i, role) })),
  }));
  return {
    entityType: "node",
    instruction: NODES_INSTRUCTION,
    available_node_roles_and_descriptions: NODE_ROLE_DESCRIPTIONS,
    custom_roles_allowed: true,
    role_groups,
    instances,
  };
}

/** The real compiled functions of one node, read through the generated executables registry (step 241) —
 *  a static-import registry, so this NEVER regex-parses functions.ts. A draft (or a node whose module fails
 *  to load) simply reports no functions. */
async function nodeFunctionCards(automation: string, slug: string): Promise<NodeFunctionCard[]> {
  try {
    const { EXECUTABLES } = await import("@/app/(projects)/projects/_generated/executables");
    const load = EXECUTABLES[`${automation}:${slug}`];
    if (!load) return [];
    const mod = await load();
    const fns = (mod as { FUNCTIONS?: unknown }).FUNCTIONS;
    if (!Array.isArray(fns)) return [];
    return fns.map((f) => {
      const o = f as { name?: string; paramsIn?: Record<string, string>; returns?: string; rules?: string[] };
      return {
        name: o.name ?? "",
        instruction: Array.isArray(o.rules) ? o.rules.join("; ") : "",
        takes: o.paramsIn ?? {},
        returns: o.returns ?? "",
      };
    });
  } catch {
    return [];
  }
}

async function automationTypeOf(automation: string): Promise<string> {
  const proj = resolveProject(automation);
  if (!proj.ok) return "stream";
  const t = await readFile(join(proj.projectDir, "_data", "automation.ts"), "utf8").catch(() => "");
  return (t.match(/AUTOMATION_TYPE[^=]*=\s*["']([a-z]+)["']/) ?? [])[1] ?? "stream";
}

/** A JSON string literal captured by regex from a _data/*.ts source → its decoded value. */
function jsonStr(m: RegExpMatchArray | null): string {
  try { return m ? (JSON.parse(m[1]) as string) : ""; } catch { return ""; }
}

// THE CREDENTIALS VIEW (step 248) — the passport surfaces the automation's declared channel keys with a
// PRESENCE flag each (never a value): the agent sees what the automation needs and what the owner already
// filled in Settings, so a present key is never asked for twice. Source of truth stays _data/channels.ts
// (the channels standard — README "settings & tests"); this is a read-only projection of it, parsed with
// the same regex approach the passport already uses on description.ts.
async function extractCredentials(projectDir: string): Promise<{ keys: { env: string; channel: string; label: string; optional: boolean; secret: boolean; present: boolean }[] }> {
  const raw = await readFile(join(projectDir, "_data/channels.ts"), "utf8").catch(() => "");
  // STRIP COMMENTS FIRST — the frozen skeleton ships a commented-out Google Calendar EXAMPLE in this very
  // file, and a naive regex read it as a live declaration (caught on automation-14's first live bundle).
  const src = raw.replace(/\/\*[\s\S]*?\*\//g, "").split(/\r?\n/).map((l) => l.replace(/\/\/.*$/, "")).join("\n");
  const names = [...src.matchAll(/name:\s*("(?:[^"\\]|\\.)*")/g)].map((m) => ({ i: m.index ?? 0, name: jsonStr(m as RegExpMatchArray) }));
  const keys: { env: string; channel: string; label: string; optional: boolean; secret: boolean }[] = [];
  for (const m of src.matchAll(/\{[^{}]*env:\s*"([A-Z][A-Z0-9_]*)"[^{}]*\}/g)) {
    const body = m[0];
    const label = /label:\s*("(?:[^"\\]|\\.)*")/.exec(body);
    const channel = [...names].reverse().find((n) => n.i < (m.index ?? 0))?.name ?? "";
    keys.push({
      env: m[1], channel,
      label: label ? jsonStr(label) : m[1],
      optional: /optional:\s*true/.test(body),
      secret: /secret:\s*true/.test(body),
    });
  }
  if (!keys.length) return { keys: [] };
  const present = await readEnvPresence(keys.map((k) => k.env));
  return { keys: keys.map((k) => ({ ...k, present: Boolean(present[k.env]) })) };
}

async function extractPassport(automation: string): Promise<unknown> {
  const proj = resolveProject(automation);
  if (!proj.ok) return { error: proj.error };
  const read = (rel: string) => readFile(join(proj.projectDir, rel), "utf8").catch(() => "");
  const [descSrc, type, instruction, readme, configSrc, howItWorks, lifecycleState, credentials] = await Promise.all([
    read("_data/description.ts"), automationTypeOf(automation),
    read("_data/instruction.md"), read("README.md"), read("_data/config.ts"),
    readHowItWorks(proj.projectDir), getLifecycleState(automation), extractCredentials(proj.projectDir),
  ]);
  const title = jsonStr(descSrc.match(/title:\s*("(?:[^"\\]|\\.)*")/));
  const description = jsonStr(descSrc.match(/description:\s*\n?\s*("(?:[^"\\]|\\.)*")/));
  const seedToggles: Record<string, boolean> = {};
  for (const m of configSrc.matchAll(/([a-z]+):\s*(true|false)/g)) seedToggles[m[1]] = m[2] === "true";
  const live = await getLiveEntities(automation);
  return {
    automation, title, description, type,
    available_types_and_descriptions: AUTOMATION_TYPE_DESCRIPTIONS,
    // THE LIFECYCLE FLAG (step 247, owner's design) — verbatim English tokens. "starter-template" = the
    // graph is still the shipped demo pattern; "real-automation" = the first development wave completed.
    // The system flips it mechanically (development-wave/complete); agent_instruction 2a explains the duty.
    lifecycleState,
    available_lifecycle_states_and_descriptions: LIFECYCLE_STATE_DESCRIPTIONS,
    // Step 248 — declared channel keys with presence flags (NEVER values): read this BEFORE asking the
    // owner for any key; present:true is never requested again.
    credentials,
    isChainedGroup: type === "chained",
    ownerInstruction: instruction.trim(),
    // The universal pair at automation level (owner 2026-07-16): the automation's own rawRequest rides the
    // entities (each object carries its own wish), so the passport's is always ''; its summary is the
    // owner-validated "How it works" text (≤300 words), falling back to the stored entity_summary row.
    rawRequest: "",
    summary: (howItWorks?.text ?? "") || description,
    howItWorks: howItWorks?.text ?? "",
    howItWorksUpdatedAt: howItWorks?.updatedAt ?? null,
    readme: readme.trim(),
    entityToggles: { ...seedToggles, ...live },
  };
}

// ─── PER-ENTITY TASK/IDENTITY SHAPES ─────────────────────────────────────────────────────────────────────
// Deliberately flat, near-identical in KIND (1-3 plain string fields) across all 9 — "what do I need to
// do" never needs entity-specific parsing, only "read these string fields." Identity stays entity-specific
// (expected — descriptive facts about the instance, not the task itself).

type NodeIdentity = { cuid: string; slug: string; name: string; status: string; draft: boolean; role: string; ioType?: string };
type NodeTask = { instruction: string; spec: string };

type EdgeIdentity = { cuid: string; name: string; from: string; to: string; status: string; draft: boolean };
type EdgeTask = { spec: string };

type UsecaseIdentity = { cuid: string; ord: number };
type UsecaseTask = { title: string; summary: string; status: string };

type ChainMemberSnapshot = { automation: string; title?: string; description?: string; type?: string; nodes?: unknown[]; error?: string };
type ChainIdentity = { members: string[]; memberSnapshots: ChainMemberSnapshot[] };
type ChainTask = { brief: string };

type StubIdentity = { toggleEnabled: boolean };
type StubTask = { brief: string };

// ─── PER-ENTITY EXTRACTORS ───────────────────────────────────────────────────────────────────────────────

async function extractNode(automation: string, withHistory: boolean): Promise<NodeArchitectureSlice> {
  const proj = resolveProject(automation);
  if (!proj.ok) return buildNodeSlice([]);
  // A CHAINED GROUP (step 234/236 — the `group`-kind subflow container on the global canvas) has no real
  // workflow of its own: its frozen skeleton still carries draft input/logic/output nodes, but the page
  // itself hides them (GroupDetailSection replaces DiagramSection). Serializing those skeleton drafts would
  // MISLEAD the reading agent — return an empty instance list; the passport's isChainedGroup:true + the
  // `chain` slice (brief + member snapshots) are the real architecture here.
  if ((await automationTypeOf(automation)) === "chained") {
    return buildNodeSlice([]);
  }
  const nodes = await listNodes(automation);
  const instances = await Promise.all(nodes.map(async (n) => {
    const files = await readNodeFiles(proj.projectDir, n.slug);
    // The role is authored in the node's own meta.ts (NodeContract.role) — the DB index carries no role
    // column, so read it from the file source (readNodeFiles already loads meta.ts). Absent → intermediate.
    const role = (files.meta.match(/\brole\s*:\s*["']([a-zA-Z0-9_-]+)["']/) ?? [])[1] ?? "intermediate";
    const ioType = (files.meta.match(/\bioType\s*:\s*["']([a-zA-Z0-9_-]+)["']/) ?? [])[1];
    const identity: NodeIdentity = { cuid: n.cuid, slug: n.slug, name: n.name, status: n.status, draft: Boolean(n.draft), role, ioType };
    // The node's SUMMARY (owner 2026-07-16): the AI-written "how it works now". The entity_summary store wins
    // when written; a node's co-located meta.ts `description` is the fallback home of the same fact.
    const storedSummary = await getSummary(automation, "node", n.cuid);
    const metaDescription = jsonStr(files.meta.match(/description:\s*\n?\s*("(?:[^"\\]|\\.)*")/));
    const summary = storedSummary || metaDescription;
    // A draft node IS its pending task (an unbuilt spec.md/instruction.ts waiting for a coder).
    //
    // A MATERIALIZED node normally has nothing pending — the brief that built it lives in history. But since
    // step 240 it can have ONE thing pending: an OPTIMIZATION. When the owner edits a live node's system
    // instruction, the PATCH stages that new instruction in the node's transport slot (it used to be
    // dispatched by the panel's own button, which the wave replaced). Surfacing it here is what puts the
    // optimization into the wave — otherwise it would be silently dropped.
    let currentTask: NodeTask | null = n.draft ? { instruction: files.instruction, spec: files.spec } : null;
    const t = await getTransport(automation, "node", n.cuid);
    const p = t?.payload as { instruction?: string; spec?: string } | undefined;
    if (!n.draft) {
      if (p?.instruction?.trim()) currentTask = { instruction: p.instruction, spec: p.spec ?? "" };
    } else if (p?.instruction?.trim()) {
      // A DRAFT's task is its spec.md — but a warning ANSWER (owner's reply, or the step-248 credentials
      // auto-resolve with its re-test mandate) lands in the transport slot. Without this merge the answer
      // was INVISIBLE for draft nodes (caught live on automation-14: the mandate never reached the bundle's
      // rawRequest). The transport text joins the draft task, so the wave and the agent see both.
      currentTask = { instruction: [files.instruction, p.instruction].filter(Boolean).join("\n\n"), spec: files.spec };
    }
    let history: EntityTaskRecord<NodeTask>[] = [];
    if (withHistory) {
      // Oldest first — a chronological story. Reads the GENERIC entity_history table (step 238 Phase 1).
      const versions = [...(await listVersionsByRef("node", n.cuid))].reverse();
      history = versions.map((v) => {
        const p = v.payload as { specSrc?: string; instructionSrc?: string };
        return { version: v.version, task: { instruction: p.instructionSrc ?? "", spec: p.specSrc ?? "" }, devStepRef: v.devStepRef, createdAt: v.createdAt };
      });
    }
    return {
      ...makeInstance(n.cuid, identity, currentTask, history, summary, await getWarning(automation, "node", n.cuid)),
      functions: await nodeFunctionCards(automation, n.slug),
    };
  }));
  return buildNodeSlice(instances);
}

// ─── THE DIAGRAM EDGES (owner 2026-07-16 — the second half of the `diagram` object) ─────────────────────
// Read from the diagram's own edge LIST (automation_diagram_edges — the fan-in fix: a node takes any number
// of incoming and outgoing edges; a second edge into a node no longer replaces the first). The list is
// seeded from the template's declared parents by syncIndexFromFiles and edited in the canvas's edge mode.
// `when` carries the TARGET's own conditions when the target is a CONDITION node — that is how a branch
// reads on the object: two edges leave lookup, one per condition gate, and only the success gate's edge
// continues to the output. Fallback (empty list, e.g. an automation never opened): derive from the parents.

export type DiagramEdge = {
  from: string; to: string; fromName: string; toName: string;
  when: string | null; rawRequest: string; summary: string;
};

async function extractDiagramEdges(automation: string): Promise<DiagramEdge[]> {
  const proj = resolveProject(automation);
  if (!proj.ok) return [];
  if ((await automationTypeOf(automation)) === "chained") return [];
  const nodes = await listNodes(automation);
  const metas = new Map<string, { parentId: string | null; ioType?: string; conditions: string[] }>();
  for (const n of nodes) {
    const files = await readNodeFiles(proj.projectDir, n.slug);
    const parentId = (files.meta.match(/parentId:\s*["']([^"']+)["']/) ?? [])[1] ?? null;
    const ioType = (files.meta.match(/\bioType\s*:\s*["']([a-zA-Z0-9_-]+)["']/) ?? [])[1];
    const condBlock = (files.meta.match(/conditions:\s*\[([\s\S]*?)\]/) ?? [])[1] ?? "";
    const conditions = [...condBlock.matchAll(/["']([^"']+)["']/g)].map((m) => m[1]);
    metas.set(n.slug, { parentId, ioType, conditions });
  }
  const bySlug = new Map(nodes.map((n) => [n.slug, n]));
  const byCuid = new Map(nodes.map((n) => [n.cuid, n]));
  const whenOf = (target: (typeof nodes)[number]): string | null => {
    const meta = metas.get(target.slug);
    return meta?.ioType === "condition" && meta.conditions.length ? meta.conditions.join("; ") : null;
  };
  const rows = await listDiagramEdges(automation);
  if (rows.length) {
    const edges: DiagramEdge[] = [];
    for (const r of rows) {
      const s = byCuid.get(r.from_cuid);
      const t = byCuid.get(r.to_cuid);
      if (!s || !t) continue;
      edges.push({ from: s.cuid, to: t.cuid, fromName: s.name, toName: t.name, when: whenOf(t), rawRequest: "", summary: "" });
    }
    return edges;
  }
  // Fallback — the declared-parent derivation (an automation whose index/edge list was never seeded).
  const edges: DiagramEdge[] = [];
  nodes.forEach((n, i) => {
    const meta = metas.get(n.slug);
    const parent =
      (n.parent_cuid ? byCuid.get(n.parent_cuid) : undefined)
      ?? (meta?.parentId ? bySlug.get(meta.parentId) : undefined)
      ?? (i > 0 ? nodes[i - 1] : undefined);
    if (!parent || parent.cuid === n.cuid) return;
    edges.push({ from: parent.cuid, to: n.cuid, fromName: parent.name, toName: n.name, when: whenOf(n), rawRequest: "", summary: "" });
  });
  return edges;
}

async function extractEdge(automation: string, withHistory: boolean): Promise<EntitySlice<EdgeTask, EdgeIdentity>> {
  const all = await listEdges();
  const edges = all.filter((e) => e.from_automation === automation || e.to_automation === automation);
  const instances = await Promise.all(edges.map(async (e) => {
    const files = await readEdgeFiles(e.cuid);
    const identity: EdgeIdentity = {
      cuid: e.cuid, name: e.name, from: e.from_automation, to: e.to_automation,
      status: e.status, draft: Boolean(e.draft),
    };
    const currentTask: EdgeTask | null = e.draft ? { spec: files.spec } : null;
    let history: EntityTaskRecord<EdgeTask>[] = [];
    if (withHistory) {
      const versions = [...(await listVersionsByRef("edge", e.cuid))].reverse();
      history = versions.map((v) => {
        const p = v.payload as { specSrc?: string };
        return { version: v.version, task: { spec: p.specSrc ?? "" }, devStepRef: v.devStepRef, createdAt: v.createdAt };
      });
    }
    // An edge belongs to no single automation — its summary rows use automation:'' like its history rows.
    return makeInstance(e.cuid, identity, currentTask, history, await getSummary("", "edge", e.cuid));
  }));
  return { entityType: "edge", instruction: ENTITY_INSTRUCTIONS.edge ?? "", instances };
}

async function extractUsecase(automation: string, withHistory: boolean): Promise<EntitySlice<UsecaseTask, UsecaseIdentity>> {
  const cases = await listCases(automation);
  const instances = await Promise.all(cases.map(async (c) => {
    const identity: UsecaseIdentity = { cuid: c.cuid, ord: c.ord };
    // A case's content IS the task until it has been reviewed/approved — "new"/"in-approval" means the
    // owner has not yet agreed the AI understood correctly, so its current text is still a pending ask.
    // Once approved+ (in-development/testing/in-use), nothing is pending — the case now describes settled
    // behaviour, not a to-do (a later edit is a NEW change, captured by history at that point).
    const currentTask: UsecaseTask | null =
      c.status === "new" || c.status === "in-approval"
        ? { title: c.title, summary: c.summary, status: c.status }
        : null;
    let history: EntityTaskRecord<UsecaseTask>[] = [];
    if (withHistory) {
      // Each edit/status transition archives the OUTGOING state (lib/use-cases.ts archiveCaseVersion,
      // called from updateCase/deleteCase before the mutation lands) — CUID-scoped like node/edge.
      const versions = [...(await listVersionsByRef("usecase", c.cuid))].reverse();
      history = versions.map((v) => {
        const p = v.payload as { title?: string; summary?: string; status?: string };
        return { version: v.version, task: { title: p.title ?? "", summary: p.summary ?? "", status: p.status ?? "" }, devStepRef: v.devStepRef, createdAt: v.createdAt };
      });
    }
    // An approved+ case's own text IS its summary (settled behaviour); a stored entity_summary row wins.
    const settled = currentTask ? "" : [c.title, c.summary].filter(Boolean).join(" — ");
    const summary = (await getSummary(automation, "usecase", c.cuid)) || settled;
    return makeInstance(c.cuid, identity, currentTask, history, summary);
  }));
  return { entityType: "usecase", instruction: ENTITY_INSTRUCTIONS.usecase ?? "", instances };
}

async function extractChain(automation: string, withHistory: boolean): Promise<EntitySlice<ChainTask, ChainIdentity>> {
  const brief = await readChainSpec(automation);
  const members = await groupMembers(automation);
  // SHALLOW member snapshots (owner's explicit "must support chained flow / group nodes"): member names
  // alone are useless to an agent designing the chain — it needs each member's identity + node surface to
  // reason about hand-offs. Shallow on purpose: identity + node names/statuses, never the members' full
  // bundles (an agent that needs a member's depth calls the master route FOR that member).
  const memberSnapshots: ChainMemberSnapshot[] = await Promise.all(members.map(async (m) => {
    const proj = resolveProject(m);
    if (!proj.ok) return { automation: m, error: proj.error };
    const [descSrc, type, nodes] = await Promise.all([
      readFile(join(proj.projectDir, "_data", "description.ts"), "utf8").catch(() => ""),
      automationTypeOf(m),
      listNodes(m),
    ]);
    return {
      automation: m,
      title: jsonStr(descSrc.match(/title:\s*("(?:[^"\\]|\\.)*")/)),
      description: jsonStr(descSrc.match(/description:\s*\n?\s*("(?:[^"\\]|\\.)*")/)),
      type,
      nodes: nodes.map((n) => ({ slug: n.slug, name: n.name, status: n.status, draft: Boolean(n.draft) })),
    };
  }));
  const identity: ChainIdentity = { members, memberSnapshots };
  const currentTask: ChainTask | null = brief.trim() ? { brief } : null;
  let history: EntityTaskRecord<ChainTask>[] = [];
  if (withHistory) {
    // Chain is AUTOMATION-SCOPED (ref='' — shared across every automation), so its history reads through
    // the automation-scoped getHistory, never the CUID ref-based helpers (step 238 Phase 4).
    const versions = await getHistory(automation, "chain", "");
    history = versions.map((v) => {
      const p = v.payload as { brief?: string };
      return { version: v.version, task: { brief: p.brief ?? "" }, devStepRef: v.devStepRef, createdAt: v.createdAt };
    });
  }
  return {
    entityType: "chain",
    instruction: ENTITY_INSTRUCTIONS.chain ?? "",
    instances: [makeInstance("", identity, currentTask, history, await getSummary(automation, "chain", ""))],
  };
}

// `fork-activation` (step 239) rides the SAME stub shape — automation-wide, one free-text brief — so it needs
// no extractor of its own. The one difference is `toggleEnabled`: it has no visibility switch (it is simply
// always there for an `instanced` automation), so extractStub reports `true` for it rather than reading a
// toggle that does not exist.
type StubEntityType = "dashboard" | "analytics" | "calendar" | "cron" | "map" | "processes" | "fork-activation" | "general";

// ─── THE DASHBOARD'S PER-TABLE SLICE (owner 2026-07-16) ─────────────────────────────────────────────────
// The dashboard holds 0..N TABLES, so one automation-wide instance hid them: requirements could only target
// "the dashboard as a whole". Now the slice carries ONE instance PER TABLE (ref = the table id) after the
// automation-wide instance (ref='' — whole-dashboard requirements, the visibility toggle). Each table's
// identity is TYPED: its columns (id/type/source, from the closed ColumnType set) and its cell ACTIONS
// (type + the authored plain-language actionDescription — what the modal does), read from the automation's
// real _data/dashboard.ts through the generated DASHBOARDS registry (never a regex parse). Per-table
// rawRequest/summary/history ride the same entity_transport/entity_history/entity_summary stores, keyed by
// the table-id ref — the wave picks a staged table requirement up automatically.

type LocalizedTextLike = string | Record<string, string>;
const localizedToString = (t: LocalizedTextLike | undefined): string =>
  typeof t === "string" ? t : t ? (t.en ?? Object.values(t)[0] ?? "") : "";

type TableColumnCard = {
  id: string; header: string; type: string; source: string;
  action?: string; actionDescription?: string; suffix?: string; liveUrl?: string;
};
type DashboardTableIdentity = {
  tableId: string; title: string; description?: string;
  columns: TableColumnCard[];
  /** Where the rows physically live — the ONE shared store output nodes write through. */
  rowStore: string;
};

async function dashboardTablesOf(automation: string): Promise<DashboardTableIdentity[]> {
  try {
    const mod = (await import("@/app/(projects)/projects/_generated/executables")) as {
      DASHBOARDS?: Record<string, () => Promise<Record<string, unknown>>>;
    };
    const load = mod.DASHBOARDS?.[automation];
    if (!load) return [];
    const config = ((await load()) as { PROJECT_DASHBOARD?: { tables?: unknown[] } }).PROJECT_DASHBOARD;
    if (!Array.isArray(config?.tables)) return [];
    return config.tables.map((raw) => {
      const t = raw as {
        id?: string; title?: LocalizedTextLike; description?: LocalizedTextLike;
        columns?: { id?: string; header?: LocalizedTextLike; type?: string; source?: string; options?: {
          action?: string; actionDescription?: LocalizedTextLike; suffix?: string; liveUrl?: string;
        } }[];
      };
      return {
        tableId: t.id ?? "",
        title: localizedToString(t.title),
        description: localizedToString(t.description) || undefined,
        columns: (t.columns ?? []).map((c) => ({
          id: c.id ?? "", header: localizedToString(c.header), type: c.type ?? "text", source: c.source ?? "",
          action: c.options?.action,
          actionDescription: localizedToString(c.options?.actionDescription) || undefined,
          suffix: c.options?.suffix, liveUrl: c.options?.liveUrl,
        })),
        rowStore: "dashboard_rows (lib/dashboard-rows.ts addRow/listRows)",
      };
    }).filter((t) => t.tableId);
  } catch {
    return [];
  }
}

async function extractDashboard(automation: string, withHistory: boolean): Promise<EntitySlice<StubTask, unknown>> {
  // The automation-wide instance (ref='') keeps working exactly as before — whole-dashboard requirements.
  const base = await extractStub("dashboard", automation, withHistory);
  const tables = await dashboardTablesOf(automation);
  const tableInstances = await Promise.all(tables.map(async (identity) => {
    const [transport, summary, warning] = await Promise.all([
      getTransport(automation, "dashboard", identity.tableId),
      getSummary(automation, "dashboard", identity.tableId),
      getWarning(automation, "dashboard", identity.tableId),
    ]);
    const briefText = (transport?.payload as { brief?: string } | undefined)?.brief ?? "";
    const currentTask: StubTask | null = briefText.trim() ? { brief: briefText } : null;
    let history: EntityTaskRecord<StubTask>[] = [];
    if (withHistory) {
      const versions = await getHistory(automation, "dashboard", identity.tableId);
      history = versions.map((v) => {
        const p = v.payload as { brief?: string };
        return { version: v.version, task: { brief: p.brief ?? "" }, devStepRef: v.devStepRef, createdAt: v.createdAt };
      });
    }
    return makeInstance(identity.tableId, identity as unknown, currentTask, history, summary, warning);
  }));
  const { COLUMN_TYPE_DESCRIPTIONS, ACTION_TYPE_DESCRIPTIONS } = await import("@/app/(projects)/projects/_shared/table-config");
  return {
    ...base,
    instances: [...base.instances, ...tableInstances],
    // The dictionaries a reading agent needs to understand any table's columns/actions (same pattern as the
    // node role/type dictionaries) — carried on the slice, once, not per table.
    ...( { available_column_types: COLUMN_TYPE_DESCRIPTIONS, available_action_types: ACTION_TYPE_DESCRIPTIONS } as object),
  } as EntitySlice<StubTask, unknown>;
}

// Dashboard/Analytics/Calendar/Map/Processes (step 238 P5-P9) — the owner writes a free-text REQUIREMENT
// brief (the "Requirement" panel in each entity's accordion), automation-scoped (ref=''), same shape as the
// chain brief. This is a data-entry surface, not a builder — no dedicated node/table like dashboard's own
// live rows (228/229); it exists purely to carry the owner's NEXT requested change through to a coding
// agent via JSON1/JSON2, same as every other entity.
async function extractStub(entityType: StubEntityType, automation: string, withHistory: boolean): Promise<EntitySlice<StubTask, StubIdentity>> {
  const [live, transport, summary, warning] = await Promise.all([
    getLiveEntities(automation),
    getTransport(automation, entityType, ""),
    getSummary(automation, entityType, ""),
    getWarning(automation, entityType, ""),
  ]);
  const identity: StubIdentity = {
    toggleEnabled: entityType === "fork-activation" ? true : Boolean(live[entityType as keyof typeof live]),
  };
  const briefText = (transport?.payload as { brief?: string } | undefined)?.brief ?? "";
  const currentTask: StubTask | null = briefText.trim() ? { brief: briefText } : null;
  let history: EntityTaskRecord<StubTask>[] = [];
  if (withHistory) {
    const versions = await getHistory(automation, entityType, "");
    history = versions.map((v) => {
      const p = v.payload as { brief?: string };
      return { version: v.version, task: { brief: p.brief ?? "" }, devStepRef: v.devStepRef, createdAt: v.createdAt };
    });
  }
  return {
    entityType,
    instruction: ENTITY_INSTRUCTIONS[entityType] ?? "",
    instances: [makeInstance("", identity, currentTask, history, summary, warning)],
  };
}

async function extractOne(entityType: EntityType, automation: string, withHistory: boolean): Promise<EntitySlice> {
  switch (entityType) {
    case "node": return extractNode(automation, withHistory);
    case "edge": return extractEdge(automation, withHistory);
    case "usecase": return extractUsecase(automation, withHistory);
    case "chain": return extractChain(automation, withHistory);
    case "dashboard": return extractDashboard(automation, withHistory);
    default: return extractStub(entityType, automation, withHistory);
  }
}

/** The DIAGRAM object (owner 2026-07-16): nodes + edges grouped under one roof, with the diagram's own
 *  static instruction (the iterative build methodology + the node budget) and its own universal pair. */
export type DiagramObject = {
  instruction: string;
  rawRequest: string;
  summary: string;
  nodes: NodeArchitectureSlice;
  edges: { instruction: string; instances: DiagramEdge[] };
};

export type ArchitectureBundle = {
  automation: string;
  format: "full-with-history" | "current-snapshot";
  /** The GENERAL instruction for the reading agent — its duties over this whole object (static, in code). */
  agent_instruction: string;
  /** The universal trio's lifecycle (trigger / success-state / blocked-state), self-described IN the JSON
   *  (step 247) — the agent learns the state machine from the object itself, not the external document. */
  agentFieldContracts: FieldContract[];
  generatedAt: string;
  /** The automation's own identity — title, description, type, the owner's instruction, README, toggles,
   *  plus the universal pair (rawRequest always ''; summary = the owner-validated "How it works"). */
  passport: unknown;
  /** Nodes + edges, grouped (owner 2026-07-16) — the single source of truth for behaviour. */
  diagram: DiagramObject;
  /** Every OTHER entity (usecase / chain / edge-links / dashboard / …) in the uniform slice shape. */
  entities: EntitySlice[];
};

/** One entity's slice, on its own — backs the per-entity extract-* sub-APIs and the wave (the master bundler
 *  below calls this same function, wrapped in Promise.allSettled for error isolation). */
export async function extractEntitySlice(entityType: EntityType, automation: string, withHistory: boolean): Promise<EntitySlice> {
  return extractOne(entityType, automation, withHistory);
}

// `fork-activation` is deliberately EXCLUDED from the architecture bundle (owner decision). Its purpose in
// the product is the activation DESIGN surface, not a development-instruction entity: a live instanced
// automation could accumulate tens of thousands of activation records, and carrying them — or even its bare
// stub — in this object adds no value to a coding agent whose job is to build the automation. What the type
// IS is already conveyed by the passport (`type` + `available_types_and_descriptions`). Its own accordion, activation quiz,
// and dedicated fork-activation-architecture/* sub-APIs are untouched — this only trims the master bundle.
// `node` is excluded from the FLAT entities[] because it moved INTO the `diagram` object (owner 2026-07-16);
// its per-entity sub-APIs still serve the node slice on its own via extractEntitySlice.
const BUNDLE_ENTITY_TYPES: EntityType[] = ENTITY_TYPES.filter((t) => t !== "fork-activation" && t !== "node");

export async function buildArchitecture(automation: string, withHistory: boolean): Promise<ArchitectureBundle> {
  // The passport is isolated the same way the entity slices are — a broken description file must not
  // take the whole bundle down with it.
  const [passport, nodeSliceResult, diagramEdges, results] = await Promise.all([
    extractPassport(automation).catch((e) => ({ error: String(e) })),
    extractNode(automation, withHistory).catch((e) => ({ ...buildNodeSlice([]), error: String(e) })),
    extractDiagramEdges(automation).catch(() => [] as DiagramEdge[]),
    Promise.allSettled(BUNDLE_ENTITY_TYPES.map((entityType) => extractEntitySlice(entityType, automation, withHistory))),
  ]);
  const entities: EntitySlice[] = results.map((r, i) => {
    if (r.status === "fulfilled") return r.value;
    return { entityType: BUNDLE_ENTITY_TYPES[i], instruction: "", instances: [], error: String(r.reason) };
  });
  return {
    automation,
    format: withHistory ? "full-with-history" : "current-snapshot",
    agent_instruction: AGENT_INSTRUCTION_CORE + (withHistory ? AGENT_INSTRUCTION_TAIL_FULL : AGENT_INSTRUCTION_TAIL_CURRENT),
    agentFieldContracts: AGENT_FIELD_CONTRACTS,
    generatedAt: new Date().toISOString(),
    passport,
    diagram: {
      instruction: DIAGRAM_INSTRUCTION,
      rawRequest: "",
      summary: "",
      nodes: nodeSliceResult,
      edges: { instruction: EDGES_INSTRUCTION, instances: diagramEdges },
    },
    entities,
  };
}
