import { cp, mkdir, readdir, rm, stat } from "node:fs/promises";
import { join, relative, sep } from "node:path";
import { resolveProject } from "@/lib/nodes";

// THE PROJECTION — the agent's sterile room (step 254.13, ROUTE-V3 law 4). Hand-off no longer means
// "here is the whole admin app": buildProjection exports the route's ESSENCE — the six born documents,
// declarations, node sources, its own helpers/types/api — into a NEUTRAL workspace outside the served
// trees. An external agent works THERE (a few thousand tokens of pure signal), and its diff comes back
// through the gated apply (254.14). Deterministic: the room is wiped and rebuilt on every call, so a
// projection is always the CURRENT truth, never an accumulation.
//
// WHAT IS PROJECTED (the essence) vs NOT (the cockpit):
//   in:  AGENTS.md CLAUDE.md WIRING-RULES.md SCALE-RULES.md PLATFORM.md README.md cron.json
//        _data/ _nodes/ (sources only — *.compiled.mjs is runtime truth and NEVER leaves the route)
//        _lib/ _types/ api/ pages/
//   out: page.tsx _components/ _meta.ts (the admin/page surface — base-layer territory, zero value to
//        a behaviour-developing agent), functions.compiled.mjs (regenerated by materialize, not authored).

const ROOM_ROOT = () => join(process.cwd(), "..", "agent-rooms");

const PROJECT_DOCS = ["AGENTS.md", "CLAUDE.md", "WIRING-RULES.md", "SCALE-RULES.md", "PLATFORM.md", "README.md", "cron.json"];
const PROJECT_DIRS = ["_data", "_nodes", "_lib", "_types", "api", "pages"];

export type ProjectionManifest = {
  ok: true;
  automation: string;
  /** Absolute room path on the server (inside /opt/fractera → mirrored into the local ai-workspace). */
  root: string;
  files: string[];
  bytes: number;
  /** bytes/4 — the standing rough token estimate. */
  tokens: number;
};

async function exists(p: string): Promise<boolean> {
  try { await stat(p); return true; } catch { return false; }
}

async function walk(dir: string): Promise<string[]> {
  let out: string[] = [];
  for (const name of await readdir(dir)) {
    const p = join(dir, name);
    if ((await stat(p)).isDirectory()) out = out.concat(await walk(p));
    else out.push(p);
  }
  return out;
}

export async function buildProjection(automation: string): Promise<ProjectionManifest | { ok: false; error: string }> {
  const proj = resolveProject(automation);
  if (!proj.ok) return { ok: false, error: proj.error };

  const room = join(ROOM_ROOT(), proj.category, proj.slug);
  await rm(room, { recursive: true, force: true });
  await mkdir(room, { recursive: true });

  for (const doc of PROJECT_DOCS) {
    const src = join(proj.projectDir, doc);
    if (await exists(src)) await cp(src, join(room, doc));
  }
  for (const dir of PROJECT_DIRS) {
    const src = join(proj.projectDir, dir);
    if (await exists(src)) {
      await cp(src, join(room, dir), {
        recursive: true,
        // The compiled artifact is RUNTIME truth (step 251's lesson: agents must never touch it) — it
        // stays home; the room carries only what an agent may author.
        filter: (s) => !s.endsWith(".compiled.mjs"),
      });
    }
  }

  const files: string[] = [];
  let bytes = 0;
  for (const f of await walk(room)) {
    files.push(relative(room, f).split(sep).join("/"));
    bytes += (await stat(f)).size;
  }
  files.sort();
  return { ok: true, automation: proj.automation, root: room, files, bytes, tokens: Math.round(bytes / 4) };
}
