// СЛОВАРЬ ШАПКИ — десять языков (en, es, fr, it, ru, de, pt, pl, tr, nl), англ. фолбэк (закон 4г).
// Живёт в папке автоматизации: наружу не ходим (закон 0). Метки меню перенесены ДОСЛОВНО из v1
// (automation-menu-i18n.ts) — фидбэк владельца «переноси один-в-один». Переводим только прозу
// интерфейса; значения enum (тип/жизненный цикл/шаринг) остаются машинными токенами (закон 4г).
export type ChromeStrings = {
  // menu chrome (faithful to v1)
  menuAria: string;
  howItWorks: string;
  automationLabel: string;
  aiProvider: string;
  aiModel: string;
  entitiesHeading: string;
  reorderAria: string; // "{name}"
  settingsItem: string;
  testsItem: string;
  dangerZone: string;
  renameAutomation: string;
  cloneAutomation: string;
  deleteAutomation: string;
  // channels section of the menu (step 293)
  channelsHeading: string;
  channelsIn: string;
  channelsOut: string;
  channelNeedsKeys: string;
  channelNoFunction: string;
  // added in v2 (the ONE new entry the owner asked for) + the no-backend placeholder
  publicPage: string;
  placeholderNote: string;
  // how-it-works modal body (public Sparkle + menu item)
  howItWorksEmpty: string;
  // send-task
  sendOpen: string;
  sendTitle: string;
  sendPlaceholder: string;
  sendSubmit: string;
  sendSending: string;
  sendSaved: string;
  sendFailed: string;
  cancel: string;
};

const I18N: Record<string, ChromeStrings> = {
  en: { channelsHeading: "Channels this automation uses", channelsIn: "Listens on", channelsOut: "Answers through", channelNeedsKeys: "keys are not set yet", channelNoFunction: "its code is not written yet", menuAria: "Automation menu", howItWorks: "How it works", automationLabel: "Automation", aiProvider: "AI provider", aiModel: "AI model", entitiesHeading: "Sections shown on this page", reorderAria: "Reorder {name}", settingsItem: "Settings", testsItem: "Tests", dangerZone: "Danger zone", renameAutomation: "Rename this automation", cloneAutomation: "Clone this automation", deleteAutomation: "Delete this automation", publicPage: "Public page", placeholderNote: "This will be available in this template soon.", howItWorksEmpty: "The answer will appear here once the automation is built.", sendOpen: "Send task", sendTitle: "Task for the automation", sendPlaceholder: "Describe what the automation should do…", sendSubmit: "Send", sendSending: "Sending…", sendSaved: "Task saved to the automation.", sendFailed: "Could not save the task.", cancel: "Cancel" },
  es: { channelsHeading: "Canales que usa esta automatización", channelsIn: "Escucha en", channelsOut: "Responde por", channelNeedsKeys: "las claves aún no están puestas", channelNoFunction: "su código aún no está escrito", menuAria: "Menú de automatización", howItWorks: "Cómo funciona", automationLabel: "Automatización", aiProvider: "Proveedor de IA", aiModel: "Modelo de IA", entitiesHeading: "Secciones mostradas en esta página", reorderAria: "Reordenar {name}", settingsItem: "Configuración", testsItem: "Pruebas", dangerZone: "Zona de peligro", renameAutomation: "Renombrar esta automatización", cloneAutomation: "Clonar esta automatización", deleteAutomation: "Eliminar esta automatización", publicPage: "Página pública", placeholderNote: "Esto estará disponible pronto en esta plantilla.", howItWorksEmpty: "La respuesta aparecerá aquí cuando se construya la automatización.", sendOpen: "Enviar tarea", sendTitle: "Tarea para la automatización", sendPlaceholder: "Describe qué debe hacer la automatización…", sendSubmit: "Enviar", sendSending: "Enviando…", sendSaved: "Tarea guardada en la automatización.", sendFailed: "No se pudo guardar la tarea.", cancel: "Cancelar" },
  fr: { channelsHeading: "Canaux utilisés par cette automatisation", channelsIn: "Écoute sur", channelsOut: "Répond par", channelNeedsKeys: "les clés ne sont pas encore renseignées", channelNoFunction: "son code n'est pas encore écrit", menuAria: "Menu d'automatisation", howItWorks: "Comment ça marche", automationLabel: "Automatisation", aiProvider: "Fournisseur d'IA", aiModel: "Modèle d'IA", entitiesHeading: "Sections affichées sur cette page", reorderAria: "Réorganiser {name}", settingsItem: "Paramètres", testsItem: "Tests", dangerZone: "Zone de danger", renameAutomation: "Renommer cette automatisation", cloneAutomation: "Cloner cette automatisation", deleteAutomation: "Supprimer cette automatisation", publicPage: "Page publique", placeholderNote: "Ceci sera bientôt disponible dans ce modèle.", howItWorksEmpty: "La réponse apparaîtra ici une fois l'automatisation construite.", sendOpen: "Envoyer une tâche", sendTitle: "Tâche pour l'automatisation", sendPlaceholder: "Décrivez ce que l'automatisation doit faire…", sendSubmit: "Envoyer", sendSending: "Envoi…", sendSaved: "Tâche enregistrée dans l'automatisation.", sendFailed: "Impossible d'enregistrer la tâche.", cancel: "Annuler" },
  it: { channelsHeading: "Canali usati da questa automazione", channelsIn: "Ascolta su", channelsOut: "Risponde tramite", channelNeedsKeys: "le chiavi non sono ancora impostate", channelNoFunction: "il suo codice non è ancora scritto", menuAria: "Menu di automazione", howItWorks: "Come funziona", automationLabel: "Automazione", aiProvider: "Provider IA", aiModel: "Modello IA", entitiesHeading: "Sezioni mostrate in questa pagina", reorderAria: "Riordina {name}", settingsItem: "Impostazioni", testsItem: "Test", dangerZone: "Zona di pericolo", renameAutomation: "Rinomina questa automazione", cloneAutomation: "Clona questa automazione", deleteAutomation: "Elimina questa automazione", publicPage: "Pagina pubblica", placeholderNote: "Sarà presto disponibile in questo modello.", howItWorksEmpty: "La risposta apparirà qui una volta costruita l'automazione.", sendOpen: "Invia attività", sendTitle: "Attività per l'automazione", sendPlaceholder: "Descrivi cosa deve fare l'automazione…", sendSubmit: "Invia", sendSending: "Invio…", sendSaved: "Attività salvata nell'automazione.", sendFailed: "Impossibile salvare l'attività.", cancel: "Annulla" },
  ru: { channelsHeading: "Каналы этой автоматизации", channelsIn: "Слушает", channelsOut: "Отвечает через", channelNeedsKeys: "ключи ещё не введены", channelNoFunction: "его код ещё не написан", menuAria: "Меню автоматизации", howItWorks: "Как это работает", automationLabel: "Автоматизация", aiProvider: "Провайдер ИИ", aiModel: "Модель ИИ", entitiesHeading: "Разделы на этой странице", reorderAria: "Переместить {name}", settingsItem: "Настройки", testsItem: "Тесты", dangerZone: "Опасная зона", renameAutomation: "Переименовать эту автоматизацию", cloneAutomation: "Клонировать эту автоматизацию", deleteAutomation: "Удалить эту автоматизацию", publicPage: "Публичная страница", placeholderNote: "Это скоро появится в этом шаблоне.", howItWorksEmpty: "Ответ появится здесь, когда автоматизация будет построена.", sendOpen: "Отправить задание", sendTitle: "Задание для автоматизации", sendPlaceholder: "Опишите, что должна делать автоматизация…", sendSubmit: "Отправить", sendSending: "Отправляю…", sendSaved: "Задание сохранено в автоматизации.", sendFailed: "Не удалось сохранить задание.", cancel: "Отмена" },
  de: { channelsHeading: "Kanäle dieser Automatisierung", channelsIn: "Hört auf", channelsOut: "Antwortet über", channelNeedsKeys: "Schlüssel sind noch nicht gesetzt", channelNoFunction: "sein Code ist noch nicht geschrieben", menuAria: "Automatisierungsmenü", howItWorks: "So funktioniert es", automationLabel: "Automatisierung", aiProvider: "KI-Anbieter", aiModel: "KI-Modell", entitiesHeading: "Auf dieser Seite angezeigte Bereiche", reorderAria: "{name} neu anordnen", settingsItem: "Einstellungen", testsItem: "Tests", dangerZone: "Gefahrenzone", renameAutomation: "Diese Automatisierung umbenennen", cloneAutomation: "Diese Automatisierung klonen", deleteAutomation: "Diese Automatisierung löschen", publicPage: "Öffentliche Seite", placeholderNote: "Dies wird bald in dieser Vorlage verfügbar sein.", howItWorksEmpty: "Die Antwort erscheint hier, sobald die Automatisierung gebaut ist.", sendOpen: "Aufgabe senden", sendTitle: "Aufgabe für die Automatisierung", sendPlaceholder: "Beschreiben Sie, was die Automatisierung tun soll…", sendSubmit: "Senden", sendSending: "Senden…", sendSaved: "Aufgabe in der Automatisierung gespeichert.", sendFailed: "Aufgabe konnte nicht gespeichert werden.", cancel: "Abbrechen" },
  pt: { channelsHeading: "Canais que esta automação usa", channelsIn: "Escuta em", channelsOut: "Responde por", channelNeedsKeys: "as chaves ainda não estão definidas", channelNoFunction: "o seu código ainda não está escrito", menuAria: "Menu de automação", howItWorks: "Como funciona", automationLabel: "Automação", aiProvider: "Provedor de IA", aiModel: "Modelo de IA", entitiesHeading: "Seções mostradas nesta página", reorderAria: "Reordenar {name}", settingsItem: "Configurações", testsItem: "Testes", dangerZone: "Zona de perigo", renameAutomation: "Renomear esta automação", cloneAutomation: "Clonar esta automação", deleteAutomation: "Eliminar esta automação", publicPage: "Página pública", placeholderNote: "Isto estará disponível em breve neste modelo.", howItWorksEmpty: "A resposta aparecerá aqui quando a automação for construída.", sendOpen: "Enviar tarefa", sendTitle: "Tarefa para a automação", sendPlaceholder: "Descreva o que a automação deve fazer…", sendSubmit: "Enviar", sendSending: "A enviar…", sendSaved: "Tarefa guardada na automação.", sendFailed: "Não foi possível guardar a tarefa.", cancel: "Cancelar" },
  pl: { channelsHeading: "Kanały tej automatyzacji", channelsIn: "Nasłuchuje na", channelsOut: "Odpowiada przez", channelNeedsKeys: "klucze nie są jeszcze wpisane", channelNoFunction: "jego kod nie jest jeszcze napisany", menuAria: "Menu automatyzacji", howItWorks: "Jak to działa", automationLabel: "Automatyzacja", aiProvider: "Dostawca AI", aiModel: "Model AI", entitiesHeading: "Sekcje pokazywane na tej stronie", reorderAria: "Zmień kolejność: {name}", settingsItem: "Ustawienia", testsItem: "Testy", dangerZone: "Strefa zagrożenia", renameAutomation: "Zmień nazwę tej automatyzacji", cloneAutomation: "Sklonuj tę automatyzację", deleteAutomation: "Usuń tę automatyzację", publicPage: "Strona publiczna", placeholderNote: "To będzie wkrótce dostępne w tym szablonie.", howItWorksEmpty: "Odpowiedź pojawi się tutaj, gdy automatyzacja zostanie zbudowana.", sendOpen: "Wyślij zadanie", sendTitle: "Zadanie dla automatyzacji", sendPlaceholder: "Opisz, co ma robić automatyzacja…", sendSubmit: "Wyślij", sendSending: "Wysyłanie…", sendSaved: "Zadanie zapisane w automatyzacji.", sendFailed: "Nie udało się zapisać zadania.", cancel: "Anuluj" },
  tr: { channelsHeading: "Bu otomasyonun kanalları", channelsIn: "Dinlediği", channelsOut: "Yanıtladığı", channelNeedsKeys: "anahtarlar henüz girilmedi", channelNoFunction: "kodu henüz yazılmadı", menuAria: "Otomasyon menüsü", howItWorks: "Nasıl çalışır", automationLabel: "Otomasyon", aiProvider: "AI sağlayıcı", aiModel: "AI modeli", entitiesHeading: "Bu sayfada gösterilen bölümler", reorderAria: "{name} sırasını değiştir", settingsItem: "Ayarlar", testsItem: "Testler", dangerZone: "Tehlike bölgesi", renameAutomation: "Bu otomasyonu yeniden adlandır", cloneAutomation: "Bu otomasyonu klonla", deleteAutomation: "Bu otomasyonu sil", publicPage: "Herkese açık sayfa", placeholderNote: "Bu, bu şablonda yakında kullanılabilir olacak.", howItWorksEmpty: "Otomasyon oluşturulduğunda yanıt burada görünecek.", sendOpen: "Görev gönder", sendTitle: "Otomasyon için görev", sendPlaceholder: "Otomasyonun ne yapması gerektiğini açıklayın…", sendSubmit: "Gönder", sendSending: "Gönderiliyor…", sendSaved: "Görev otomasyona kaydedildi.", sendFailed: "Görev kaydedilemedi.", cancel: "İptal" },
  nl: { channelsHeading: "Kanalen van deze automatisering", channelsIn: "Luistert op", channelsOut: "Antwoordt via", channelNeedsKeys: "sleutels zijn nog niet ingevuld", channelNoFunction: "de code is nog niet geschreven", menuAria: "Automatiseringsmenu", howItWorks: "Hoe het werkt", automationLabel: "Automatisering", aiProvider: "AI-provider", aiModel: "AI-model", entitiesHeading: "Secties op deze pagina", reorderAria: "{name} herordenen", settingsItem: "Instellingen", testsItem: "Tests", dangerZone: "Gevarenzone", renameAutomation: "Deze automatisering hernoemen", cloneAutomation: "Deze automatisering klonen", deleteAutomation: "Deze automatisering verwijderen", publicPage: "Openbare pagina", placeholderNote: "Dit komt binnenkort beschikbaar in deze sjabloon.", howItWorksEmpty: "Het antwoord verschijnt hier zodra de automatisering is gebouwd.", sendOpen: "Taak versturen", sendTitle: "Taak voor de automatisering", sendPlaceholder: "Beschrijf wat de automatisering moet doen…", sendSubmit: "Versturen", sendSending: "Versturen…", sendSaved: "Taak opgeslagen in de automatisering.", sendFailed: "Kon de taak niet opslaan.", cancel: "Annuleren" },
};

/** The chrome strings for a two-letter code, English until/unless a match is found. */
export function chromeStrings(lang: string): ChromeStrings {
  return I18N[lang.toLowerCase().slice(0, 2)] ?? I18N.en;
}

/** A machine enum token shown as a badge: never translated (rule 4г), only the hyphen turned to a space. */
export function badgeLabel(token: string): string {
  return token.replace(/-/g, " ");
}
