// СЛОВАРЬ ПУЛЬТА ЗАПУСКА — десять языков (en, es, fr, it, ru, de, pt, pl, tr, nl), англ. фолбэк (закон 4г).
// Живёт в папке вкладки: наружу не ходим (закон 0). Переводится только проза интерфейса; ключи параметров,
// имена узлов и значения enum остаются машинными токенами.
export type ControlPanelStrings = {
  ask: string;
  asking: string;
  required: string;
  optional: string;
  fill: string; // "{k}" — перечень незаполненных обязательных полей
  refused: string; // "{k}" — обучающий отказ движка
  done: string;
  settings: string;
  settingsHint: string;
  noParams: string;
  paramKey: string;
  paramType: string;
  noComponent: string; // "{k}" — ядро объявило пульт, файла под него нет
  failed: string; // прогон не удался, а причины узел не назвал
  tasks: string; // список задач автоматизации над полем ввода (доктрина масштаба)
  tasksHint: string; // объяснение НА ЯЗЫКЕ ИНТЕРФЕЙСА, что это за кнопки (сами подписи — данные владельца)
  price: string; // цена прогона: "{f}" функций узлов, "{m}" вызовов модели (доктрина масштаба)
  recalledFrom: string; // 330.8 — заголовок над выдержками, поднятыми из долгой памяти
};

export const CONTROL_PANEL_I18N: Record<string, ControlPanelStrings> = {
  en: { ask: "Ask", asking: "Asking…", required: "required", optional: "optional", fill: "Fill in: {k}", refused: "The automation refused: {k}", done: "Done", settings: "Request settings", settingsHint: "What this control panel asks for. The fields come from the core — change the core, the panel changes.", noParams: "This panel declares no fields yet.", paramKey: "Field", paramType: "Type", noComponent: "The core declares the control panel «{k}», but there is no file for it in _components/control-panel/.", failed: "The request could not be completed.", tasksHint: "Press a task the owner described, then say what to run it on. Task names are the owner's own words, in his language.", price: "Cost of this run: {f} node functions · {m} model calls", recalledFrom: "Recalled from earlier conversations", tasks: "What I can do" },
  es: { ask: "Consultar", asking: "Consultando…", required: "obligatorio", optional: "opcional", fill: "Completa: {k}", refused: "La automatización rechazó: {k}", done: "Listo", settings: "Ajustes de la consulta", settingsHint: "Lo que pide este panel. Los campos vienen del núcleo: cambia el núcleo y cambia el panel.", noParams: "Este panel aún no declara campos.", paramKey: "Campo", paramType: "Tipo", noComponent: "El núcleo declara el panel «{k}», pero no hay archivo para él en _components/control-panel/.", failed: "No se pudo completar la solicitud.", tasksHint: "Pulse una tarea descrita por el propietario y luego indique con qué ejecutarla. Los nombres son palabras del propietario, en su idioma.", price: "Coste de esta ejecución: {f} funciones de nodo · {m} llamadas al modelo", recalledFrom: "Recuperado de conversaciones anteriores", tasks: "Lo que puedo hacer" },
  fr: { ask: "Demander", asking: "Demande…", required: "obligatoire", optional: "facultatif", fill: "Remplissez : {k}", refused: "L'automatisation a refusé : {k}", done: "Terminé", settings: "Réglages de la demande", settingsHint: "Ce que demande ce panneau. Les champs viennent du noyau : changez le noyau, le panneau change.", noParams: "Ce panneau ne déclare encore aucun champ.", paramKey: "Champ", paramType: "Type", noComponent: "Le noyau déclare le panneau « {k} », mais aucun fichier ne lui correspond dans _components/control-panel/.", failed: "La demande n'a pas pu aboutir.", tasksHint: "Appuyez sur une tâche décrite par le propriétaire, puis dites sur quoi l'exécuter. Les intitulés sont les mots du propriétaire, dans sa langue.", price: "Coût de cette exécution : {f} fonctions de nœud · {m} appels au modèle", recalledFrom: "Retrouvé dans des conversations passées", tasks: "Ce que je peux faire" },
  it: { ask: "Chiedi", asking: "Richiesta…", required: "obbligatorio", optional: "facoltativo", fill: "Compila: {k}", refused: "L'automazione ha rifiutato: {k}", done: "Fatto", settings: "Impostazioni della richiesta", settingsHint: "Cosa chiede questo pannello. I campi vengono dal nucleo: cambia il nucleo e cambia il pannello.", noParams: "Questo pannello non dichiara ancora campi.", paramKey: "Campo", paramType: "Tipo", noComponent: "Il nucleo dichiara il pannello «{k}», ma non esiste un file per esso in _components/control-panel/.", failed: "Non è stato possibile completare la richiesta.", tasksHint: "Premi un'attività descritta dal proprietario, poi indica su cosa eseguirla. I titoli sono parole del proprietario, nella sua lingua.", price: "Costo di questa esecuzione: {f} funzioni di nodo · {m} chiamate al modello", recalledFrom: "Recuperato da conversazioni precedenti", tasks: "Cosa posso fare" },
  ru: { ask: "Запросить", asking: "Запрашиваю…", required: "обязательное", optional: "необязательное", fill: "Заполните: {k}", refused: "Автоматизация отказала: {k}", done: "Готово", settings: "Настройка запроса", settingsHint: "Что спрашивает этот пульт. Поля берутся из ядра — меняется ядро, меняется пульт.", noParams: "Пульт пока не объявил ни одного поля.", paramKey: "Поле", paramType: "Тип", noComponent: "Ядро объявило пульт «{k}», но файла под него нет в _components/control-panel/.", failed: "Запрос выполнить не удалось.", tasksHint: "Нажмите задачу, описанную владельцем, и скажите, на чём её выполнить. Названия задач — слова владельца на его языке.", price: "Цена прогона: {f} функций узлов · {m} вызовов модели", recalledFrom: "Вспомнилось из прошлых разговоров", tasks: "Что я умею" },
  de: { ask: "Abfragen", asking: "Abfrage…", required: "erforderlich", optional: "optional", fill: "Ausfüllen: {k}", refused: "Die Automatisierung hat abgelehnt: {k}", done: "Fertig", settings: "Anfrage-Einstellungen", settingsHint: "Wonach dieses Pult fragt. Die Felder kommen aus dem Kern — ändere den Kern, ändert sich das Pult.", noParams: "Dieses Pult deklariert noch keine Felder.", paramKey: "Feld", paramType: "Typ", noComponent: "Der Kern deklariert das Pult «{k}», aber es gibt keine Datei dafür in _components/control-panel/.", failed: "Die Anfrage konnte nicht ausgeführt werden.", tasksHint: "Wählen Sie eine vom Eigentümer beschriebene Aufgabe und sagen Sie dann, worauf sie angewendet wird. Die Titel sind die Worte des Eigentümers, in seiner Sprache.", price: "Kosten dieses Laufs: {f} Knotenfunktionen · {m} Modellaufrufe", recalledFrom: "Aus früheren Gesprächen erinnert", tasks: "Was ich kann" },
  pt: { ask: "Consultar", asking: "A consultar…", required: "obrigatório", optional: "opcional", fill: "Preencha: {k}", refused: "A automação recusou: {k}", done: "Pronto", settings: "Definições do pedido", settingsHint: "O que este painel pergunta. Os campos vêm do núcleo — muda o núcleo, muda o painel.", noParams: "Este painel ainda não declara campos.", paramKey: "Campo", paramType: "Tipo", noComponent: "O núcleo declara o painel «{k}», mas não há ficheiro para ele em _components/control-panel/.", failed: "Não foi possível concluir o pedido.", tasksHint: "Carregue numa tarefa descrita pelo proprietário e depois diga sobre o que executá-la. Os títulos são palavras do proprietário, na sua língua.", price: "Custo desta execução: {f} funções de nó · {m} chamadas ao modelo", recalledFrom: "Recuperado de conversas anteriores", tasks: "O que eu posso fazer" },
  pl: { ask: "Zapytaj", asking: "Pytam…", required: "wymagane", optional: "opcjonalne", fill: "Uzupełnij: {k}", refused: "Automatyzacja odmówiła: {k}", done: "Gotowe", settings: "Ustawienia zapytania", settingsHint: "O co pyta ten pulpit. Pola pochodzą z rdzenia — zmień rdzeń, zmieni się pulpit.", noParams: "Ten pulpit nie deklaruje jeszcze pól.", paramKey: "Pole", paramType: "Typ", noComponent: "Rdzeń deklaruje pulpit «{k}», ale nie ma dla niego pliku w _components/control-panel/.", failed: "Nie udało się zrealizować zapytania.", tasksHint: "Naciśnij zadanie opisane przez właściciela, a potem powiedz, na czym je wykonać. Nazwy zadań to słowa właściciela, w jego języku.", price: "Koszt tego przebiegu: {f} funkcji węzłów · {m} wywołań modelu", recalledFrom: "Przypomniane z wcześniejszych rozmów", tasks: "Co potrafię" },
  tr: { ask: "Sorgula", asking: "Sorgulanıyor…", required: "zorunlu", optional: "isteğe bağlı", fill: "Doldurun: {k}", refused: "Otomasyon reddetti: {k}", done: "Tamam", settings: "İstek ayarları", settingsHint: "Bu panelin ne sorduğu. Alanlar çekirdekten gelir — çekirdeği değiştir, panel değişir.", noParams: "Bu panel henüz alan tanımlamıyor.", paramKey: "Alan", paramType: "Tür", noComponent: "Çekirdek «{k}» panelini tanımlıyor ama _components/control-panel/ içinde ona ait dosya yok.", failed: "İstek tamamlanamadı.", tasksHint: "Sahibinin tanımladığı bir görevi seçin, sonra neyin üzerinde çalıştırılacağını söyleyin. Görev adları sahibinin kendi dilindeki sözleridir.", price: "Bu çalıştırmanın maliyeti: {f} düğüm işlevi · {m} model çağrısı", recalledFrom: "Önceki konuşmalardan hatırlandı", tasks: "Neler yapabilirim" },
  nl: { ask: "Opvragen", asking: "Bezig…", required: "verplicht", optional: "optioneel", fill: "Vul in: {k}", refused: "De automatisering weigerde: {k}", done: "Klaar", settings: "Aanvraaginstellingen", settingsHint: "Wat dit paneel vraagt. De velden komen uit de kern — verander de kern en het paneel verandert mee.", noParams: "Dit paneel declareert nog geen velden.", paramKey: "Veld", paramType: "Type", noComponent: "De kern declareert het paneel «{k}», maar er is geen bestand voor in _components/control-panel/.", failed: "Het verzoek kon niet worden voltooid.", tasksHint: "Kies een taak die de eigenaar heeft beschreven en zeg waarop die moet draaien. De titels zijn de woorden van de eigenaar, in zijn taal.", price: "Kosten van deze run: {f} knooppuntfuncties · {m} modelaanroepen", recalledFrom: "Herinnerd uit eerdere gesprekken", tasks: "Wat ik kan doen" },
};

export const controlPanelStrings = (lang: string): ControlPanelStrings =>
  CONTROL_PANEL_I18N[lang.slice(0, 2)] ?? CONTROL_PANEL_I18N.en;

// Текст из ядра читает ОДНА общая функция на всю автоматизацию — см. `_components/shared/localized.ts`.
// Здесь только реэкспорт, чтобы вкладка звала её привычным именем.
export { pick } from "../shared/localized";
