// ─────────────────────────────────────────────────────────────────────────────
// parser-fs — ONE universal, config-driven post-list generator (SHARED engine
// brick, NOT versioned). Installed copy-if-absent by the Frozen Template
// Constructor so the slot can auto-discover co-located documents.
//
// Why: documents (news/docs/…) are co-located static route folders. The index
// page needs a list of them, but Turbopack needs STATICALLY resolvable imports —
// so the list can't be discovered at runtime. This scans the filesystem at BUILD
// time and GENERATES `_list.generated.ts` (static imports + a POSTS array). The
// runtime stays 100% static / no-JS; nobody hand-maintains a list.
//
// The composer appends one COLLECTIONS entry per composed tab (registerCollection)
// and ALSO writes the tab's _list.generated.ts directly at compose time, so the
// first build works even before this runs. Adding a post later = drop a folder;
// `npm run gen:lists` (or predev/prebuild) regenerates the list.
//
// Node ESM, zero deps — runs with bare `node lib/parser-fs.mjs` on any Node.
// ─────────────────────────────────────────────────────────────────────────────

import { readdirSync, existsSync, writeFileSync, statSync } from 'node:fs'
import { join } from 'node:path'

// One entry per co-located tab. The composer appends here. Starts empty.
const COLLECTIONS = [
]

function findPostSlugs(dir) {
  if (!existsSync(dir)) return []
  return readdirSync(dir)
    .filter(name => !name.startsWith('_') && !name.startsWith('[') && !name.startsWith('.'))
    .filter(name => statSync(join(dir, name)).isDirectory())
    .filter(name => existsSync(join(dir, name, '_data', 'index.ts')))
    .sort()
}

function generate({ dir, type, typeModule }) {
  if (!existsSync(dir)) return { out: dir, count: 0, skipped: true }
  const slugs = findPostSlugs(dir)
  const imports = slugs.map((slug, i) => `import { data as p${i} } from './${slug}/_data'`).join('\n')
  const arr = slugs.map((_, i) => `p${i}`).join(', ')
  const body = `// AUTO-GENERATED by lib/parser-fs.mjs — DO NOT EDIT.
// Regenerated on every build/dev (npm prebuild/predev). Gitignored.
import type { ${type} } from '${typeModule}'
${imports}

export const POSTS: ${type}[] = [${arr}]
`
  const out = join(dir, '_list.generated.ts')
  writeFileSync(out, body, 'utf8')
  return { out, count: slugs.length }
}

let total = 0
for (const c of COLLECTIONS) {
  const r = generate(c)
  if (r.skipped) { console.log(`parser-fs: ${c.dir} (missing, skip)`); continue }
  total += r.count
  console.log(`parser-fs: ${r.out} (${r.count} posts)`)
}
console.log(`parser-fs: generated ${COLLECTIONS.length} list(s), ${total} posts total`)
