import type React from "react";

// Z-index layers. Ported verbatim from the 22slots reference (config/ui/z-index.config.ts).
export const Z_INDEX = {
  BACKGROUND: -1,
  SLOT_BACKGROUND: 0,
  SLOT_CONTENT: 1,
  BASE: 0,
  PROMO_SCREEN: 10,

  CENTER_STATIC: 10,
  CENTER_STATIC_HEADER: 10,
  CENTER_STATIC_FOOTER: 10,
  CENTER_BREADCRUMB: 11,

  CENTER_DYNAMIC: 20,
  CENTER_DYNAMIC_HEADER: 20,
  CENTER_DYNAMIC_FOOTER: 20,

  LEFT: 30,
  LEFT_HEADER: 30,
  LEFT_FOOTER: 30,
  LEFT_DRAWER: 32,
  LEFT_MODAL: 34,

  RIGHT: 40,
  RIGHT_HEADER: 40,
  RIGHT_FOOTER: 40,
  RIGHT_DRAWER: 42,
  RIGHT_MODAL: 44,

  CODE_GENERATOR: 45,

  AUTH_PAGE: 60,

  DROPDOWN: 50,
  POPOVER: 50,

  SLOT_PAGES_MENU: 51,
  SLOT_PAGES_MENU_DROPDOWN: 52,
  SLOT_PAGES_MENU_SUB: 53,

  HEADER: 100,
  HEADER_POPOVER: 101,
  HEADER_POPOVER_CONTENT: 150,
  FOOTER: 100,
  FOOTER_MENUBAR: 101,
  FOOTER_DRAWER_OVERLAY: 101,
  FOOTER_DRAWER: 102,
  FOOTER_MODAL: 9999,
  ADD_ROUTE_POPOVER: 105,
  FRACTAL_DEPTH_0: 5,
  FRACTAL_DEPTH_1: 6,
  FRACTAL_DEPTH_2: 7,
  FRACTAL_DEPTH_3: 8,
  FRACTAL_DEPTH_4: 9,
  FRACTAL_DEPTH_5: 9,
  SLOT_RESIZE_HANDLE: 10,

  FRACTAL_HEIGHT_POPOVER: 110,
  DESKTOP_ONLY_DIALOG: 200,
  FRACTAL_TREE_DIALOG: 200,
  FRACTAL_SUB_DIALOG: 210,

  MENU_CATEGORY_DIALOG: 200,
  MENU_CATEGORY_SUB_DIALOG: 210,
  TRANSLATE_INSTRUCTION_DIALOG: 220,

  HEADER_SETTINGS_DIALOG: 200,
  FOOTER_MENU_DIALOG: 200,

  MOBILE_NAV_MENU: 160,

  FINE_TUNE_BORDER: 43,
  FINE_TUNE_ICON: 44,

  TOAST: 110,
  NOTIFICATION: 110,

  TOOLTIP: 200,
  CRITICAL_ALERT: 130,
  LANGUAGE_SWITCH_DIALOG: 220,

  BRAND_BOOK_RESET_DIALOG: 300,

  MARKETPLACE_PAY_DIALOG: 200,
  MARKETPLACE_REVIEW_DIALOG: 210,

  USER_DASHBOARD_DIALOG: 200,
  USER_DASHBOARD_SUB_DIALOG: 210,

  WIDGET_SPEC_DIALOG: 200,
  WIDGET_SPEC_SUB_DIALOG: 210,
} as const;

export type ZIndexLevel = (typeof Z_INDEX)[keyof typeof Z_INDEX];

export function getZIndexStyle(layer: keyof typeof Z_INDEX): React.CSSProperties {
  return { zIndex: Z_INDEX[layer] };
}

export function getZIndexValue(layer: keyof typeof Z_INDEX): number {
  return Z_INDEX[layer];
}
