import type { {{TAB_PASCAL}}Base } from '../../_lib/types'

// FROZEN ARCHETYPE TEMPLATE — content-collection placeholder post (English base).
// Lorem-ipsum body that INHERITS the ideal post architecture: subtitle, H2/H3
// sections feeding the table of contents, a quote, a list, the mandatory root
// anchor, a founder note, and a FAQ. Replace the copy; keep the shape.
export const en: {{TAB_PASCAL}}Base = {
  title: '{{LABEL}} placeholder #{{SAMPLE_INDEX}} — replace this title',
  seoTitle: '{{LABEL}} placeholder #{{SAMPLE_INDEX}}',
  subtitle:
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. This is a thawed placeholder from the frozen content-collection archetype.',
  description:
    'A placeholder article generated by the frozen content-collection archetype. It inherits the full page standard — SEO, structured data, table of contents and FAQ — so you only replace the text.',
  summary:
    'Placeholder article from the frozen content-collection archetype — replace the copy, keep the structure.',
  keywords: '{{LABEL}}, placeholder, agentic engineering',
  blocks: [
    { kind: 'p', text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. This post was thawed from a frozen archetype by the [Agentic Engineering Infrastructure](/en) — no code was generated to create it.' },
    { kind: 'h2', text: 'First section heading' },
    { kind: 'p', text: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore.' },
    { kind: 'h3', text: 'A supporting sub-heading' },
    { kind: 'p', text: 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error.' },
    { kind: 'list', items: ['First placeholder point', 'Second placeholder point', 'Third placeholder point'] },
    { kind: 'h2', text: 'Second section heading' },
    { kind: 'p', text: 'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.' },
    { kind: 'quote', text: 'A short placeholder pull-quote — swap it for a real one.' },
    { kind: 'founder', text: 'Founder placeholder note. Replace with a closing thought; the author card renders automatically.' },
  ],
  faq: [
    { q: 'Is this a real article?', a: 'No — it is placeholder copy from the frozen content-collection archetype. Replace it with your own.' },
    { q: 'How was it created?', a: 'By thawing a frozen archetype: pure file copy plus token substitution, with no LLM code generation.' },
    { q: 'How do I add another one?', a: 'Add a co-located post folder (or thaw again); the list regenerates itself via parser-fs.' },
  ],
}
